### ISSUE TITLE
Solar data including negative generation data

### ISSUE THREAD

**Issue by williamjeccles** [macxq/foxess-ha#10]
I know that solar panels do have an energy drain during the night (losses) but this appears to be reporting this drain in the data which is causing some odd behaviour on the graphs. Also, notice the massive draw shown on nearly every night reporting data. I'm seeing the same on all three of my properties that I have this same foxess setup on so not isolated to one house.

I would like a way to ignore negative data, i.e if it's -0.2 just report it as 0 so it doesn't mess the reporting data of generation up.

Screenshots of examples:
https://ibb.co/VvQ4W5m
https://ibb.co/BKbX6Vx

Notice the reporting data dips under 0 every night

**Comment by williamjeccles** [comment]
On review, I understand that the Foxess Cloud data is resetting the sensor.foxess_solar to 0 every day at midnight which is causing the sharp drop in production. I'm unsure how to resolve this so that it would show the true generation only.

**Comment by Daibutt** [comment]
Hi @williamjeccles,

I got round the negative value thing by doing this;
https://github.com/macxq/foxess-ha/issues/2#issuecomment-964997644

**Comment by williamjeccles** [comment]
hi @Daibutt,

Thanks for pointing this out, it's exactly what I was looking for!

I'm slightly confused how exactly I set this up. 
I seem to be getting config errors when I attempt to copy and paste the following directly into my main /config/configuration.yaml is this the correct config to edit? What am I doing wrong? If you had a working example that would be awesome.

platform: integration
   source: sensor.foxess_pv1_power
   name: pv1_sum
   unit_time: h
   round: 2
platform: integration
   source: sensor.foxess_pv2_power
   name: pv2_sum
   unit_time: h
   round: 2

**Comment by Daibutt** [comment]
@williamjeccles 
This maybe a yaml indent thing. I am not an expert by any stretch of the imagination!
I only have the basic HA file editor & usually have loads of trouble with this. I think there are some editors that can help you out with indentation.
I usually solve by trial and error, entering one line at a time and waiting till I get the green tick in the editor and move on to the next line.
Here's a acsreenshot of my configuration.yaml to give you an idea of what mine looks like;
![image](https://user-images.githubusercontent.com/69276073/144874492-27eeabd2-4051-49d5-b7b1-561cd2fdf4df.png)

It looks like it is dash space before integration and then space space before the other lines (for each sensor)

**Comment by Daibutt** [comment]
@williamjeccles 
If you don't have a "sensor" section in your config you'll need to add this before the code above;
![image](https://user-images.githubusercontent.com/69276073/144877538-318a5d63-df49-4260-b207-80f2f689a509.png)

If you do, just add this in to that section, below "sensor:"

Apologies to anybody reading this that understands the configuration.yaml formatting !! ;)

**Comment by williamjeccles** [comment]
Perfect, got it all working now thank you!

**Comment by Daibutt** [comment]
Awesome!

**Comment by up661114** [comment]
Hi I'm trying to get this to work but no data seems to be working on it, any ideals?
