### ISSUE TITLE
Unable to see/add integration

### ISSUE THREAD

**Issue by mdeakin99** [macxq/foxess-ha#100]
Hi

- Downloaded via HACS and rebooted
- Added sensor (username/password/ID) to confirguration.yaml

Was expecting to see the integration/devices/entities appear in 'Integrations' but nothing there.  Confirmed no devices/entities starting with 'fox'.

Was trying to find the error logs but couldn't find them. 

Let me know anything you would like me to do in order to troubleshoot

**Comment by volker67** [comment]
try this 

https://github.com/macxq/foxess-ha/issues/93#issuecomment-1319326849
regards

**Comment by mdeakin99** [comment]
Will give that a try (as long as I can figure out how to).  Am I right in thinking this means I can’t keep the core up to date or just I need to update in this specific order?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by koendruyts** [comment]
Hi,

I have also installation issues for this first time installation.
 
Tried to install  v.0.2.0b (latest) "FoxESS and Home Assistant integration" 
1. Downloaded via HACS and rebooted
2. Added sensor (username/password/ID) to confirguration.yaml

Home Assistant 2023.1.2
Supervisor 2022.12.1
Operating System 9.4
Frontend-versie: 20230104.0 - latest

Error logs:
Logger: homeassistant.setup
Source: setup.py:359
First occurred: 14:15:09 (1 occurrences)
Last logged: 14:15:09
Unable to prepare setup for platform foxess.sensor: Unable to set up component.

Logger: homeassistant.setup
Source: custom_components/foxess/__init__.py:85
Integration: foxess (documentation, issues)
First occurred: 14:15:09 (1 occurrences)
Last logged: 14:15:09

Error during setup of component foxess
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/foxess/__init__.py", line 85, in async_setup
    config =  hass_config[DOMAIN]
KeyError: 'foxess'

Any advise how to solve this?

Thx

**Comment by mdeakin99** [comment]
I copied the instructions in https://github.com/macxq/foxess-ha/issues/93#issuecomment-1319326849 but didn’t downgrade the version I was using,  just made the change to the file and it worked for me.

**Comment by koendruyts** [comment]
Thx
I tried it and no errors anymore but still no values.
Can you confirm that line 177 is the below one
"super().__init__(coordinator, name, deviceID,"Generation Power")"

that should be replaced like in #93 (comment)<https://github.com/macxq/foxess-ha/issues/93#issuecomment-1319326849> with payloadAuth = f'user={username}&password={hashedPassword}'
[https://opengraph.githubassets.com/8caac60da0a16db6ffd054b74440679c1a711fc1327f52c9392d0c07b8822aa4/macxq/foxess-ha/issues/93]<https://github.com/macxq/foxess-ha/issues/93#issuecomment-1319326849>
newbie problem cant get fox cloud to work with ha 2022.11.3 #93<https://github.com/macxq/foxess-ha/issues/93#issuecomment-1319326849>
The text was updated successfully, but these errors were encountered:
github.com


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by mdeakin99** [comment]
It’s the one that looks like the following but not quite the same

payloadAuth = f'user={username}&password={hashedPassword}'

On 11 Jan 2023, at 15:10, koendruyts ***@***.***> wrote:

﻿

Thx
I tried it and no errors anymore but still no values.
Can you confirm that line 177 is the below one
"super().__init__(coordinator, name, deviceID,"Generation Power")"

that should be replaced like in #93 (comment)<https://github.com/macxq/foxess-ha/issues/93#issuecomment-1319326849> with payloadAuth = f'user={username}&password={hashedPassword}'
[https://opengraph.githubassets.com/8caac60da0a16db6ffd054b74440679c1a711fc1327f52c9392d0c07b8822aa4/macxq/foxess-ha/issues/93]<https://github.com/macxq/foxess-ha/issues/93#issuecomment-1319326849>
newbie problem cant get fox cloud to work with ha 2022.11.3 #93<https://github.com/macxq/foxess-ha/issues/93#issuecomment-1319326849>
The text was updated successfully, but these errors were encountered:
github.com


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by koendruyts** [comment]
That line is located in file /config/custom_components/foxess/__init__.py and not in sensor...However I changed as proposed but still no values...I noted that other users have the same issue...Any more advise?

**Comment by mdeakin99** [comment]
It’s a while since I did it so not sure what else I did to get it working.  I am pretty sure I messaged here to say ‘it’s still not working’ and then suddenly it all appeared so perhaps give it an hour or so

**Comment by macxq** [comment]
fixed in v0.16  thanks to @guba91
