### ISSUE TITLE
Unable to prepare setup

### ISSUE THREAD

**Issue by ckay111** [macxq/foxess-ha#104]
Logger: homeassistant.setup
Source: setup.py:359
First occurred: 15:53:55 (1 occurrences)
Last logged: 15:53:55
Unable to prepare setup for platform foxess.sensor: Unable to set up component.

Does anybody else have these problems?

**Comment by essenemari** [comment]
more than likely, you have HA version later than 2022.10.5. If so, integration stops to work. For around version 2022.11, there is workaround [#93 ](https://github.com/macxq/foxess-ha/issues/93#issuecomment-1319326849). 
For me, with HA 2023.1.0, it does not work neither (I mean, integration as is does not work. Not sure about workaround).

**Comment by ckay111** [comment]
Damn it.

**Comment by koendruyts** [comment]
I have the same problem and workaround 93 does not work either...hope for resolution...

**Comment by tomaskun** [comment]
I have same problem. Just waiting for solution...

**Comment by tomaskun** [comment]
I'm getting ,,Timeout while fetching data: https://www.foxesscloud.com/c/v0/user/login"

**Comment by macxq** [comment]
fixed in v0.16 thanks to @guba91
