### ISSUE TITLE
Entity has a negative state (version v0.18)

### ISSUE THREAD

**Issue by ruralleafowner** [macxq/foxess-ha#113]
![Screenshot 2023-01-28 at 07 22 43](https://user-images.githubusercontent.com/123672281/215253070-ba978a19-279f-49a0-9cc1-cf89a00fcb79.jpg)
Entity has a negative state
The following entities have a negative state while a positive state is expected:
sensor.foxess_solar (-0.7)

**Comment by macxq** [comment]
Does the new version solved the issues ?
