### ISSUE TITLE
Foxess-ha not visible in HACS

### ISSUE THREAD

**Issue by miost1** [macxq/foxess-ha#122]
Foxess-ha is not visible in HACS. I cannot integrate it, also manual installation fails.
What should be done ?

 Home Assistant 2023.2.5 Supervisor 2023.01.1 Operating System 9.5 Interfejs użytkownika: 20230202.0 - latest

**Comment by macxq** [comment]
> Foxess-ha is not visible in HACS. 

please provide screenshot of searching for it

**Comment by miost1** [comment]
![foxess-ha - none](https://user-images.githubusercontent.com/79276715/221972364-0dfa691e-41d3-49e0-b652-de873bb07710.JPG)
 The same on the website: https://www.home-assistant.io/integrations/#search/fox

![foxess-ha - none1](https://user-images.githubusercontent.com/79276715/221973833-951fcffd-eb03-46b1-aa9d-928b05af12c9.JPG)
