### ISSUE TITLE
Solar Energy shows Negative values as first reading of the Day (in Energy Charts)

### ISSUE THREAD

**Issue by r-amado** [macxq/foxess-ha#123]
Each day, the first value presented in the Energy Chart of HA shows a negative value that equals the total production of the day before (-1*x). 
![solar_energychart](https://user-images.githubusercontent.com/89645023/221660321-be18bfb4-b1dd-4a98-9484-d7a3187ddf72.png)

**Comment by iancg** [comment]
I've picked up your fix, but it doesn't appear to have helped - I think the reason is that the underlying energy component is expecting an ever increasing number and the number resets to zero each day.  I think maybe we need to use the Total Yield value from the FoxESSCloud data rather than the Today Yield?

![image](https://user-images.githubusercontent.com/1828481/222388316-a72c8a4b-ca64-469b-af4d-9cadcb7a9ef0.png)

My large -ve value always appears at midnight

![image](https://user-images.githubusercontent.com/1828481/222388633-8d902928-d317-402d-a659-41d756af2299.png)

**Comment by macxq** [comment]
it this issue still occurs?

**Comment by FraWi1963** [comment]
Yes, it does.

<img width="273" alt="Screenshot 2023-04-13 081212" src="https://user-images.githubusercontent.com/129761382/231669539-d7c7019f-661f-4cae-969f-3e23e1cb8e8d.png">

**Comment by macxq** [comment]
@FraWi1963 which version of the integration you are on ?

**Comment by FraWi1963** [comment]
v 0.24, Update 2 hours ago.

**Comment by FraWi1963** [comment]
Home Assistant 2023.4.3

**Comment by macxq** [comment]
you have installation with batteries ? i do not have them, so hard to replicate that for me.

Can you provide screen shot of history tab for Solar entity from the whole week when this anomaly headend ?

**Comment by FraWi1963** [comment]
Entity energy_generated

<img width="1706" alt="Screenshot 2023-04-13 113101" src="https://user-images.githubusercontent.com/129761382/231718592-7a01edfc-3aea-44c0-a72b-dea225a07918.png">

**Comment by FraWi1963** [comment]
I use energy-generated in the energy dashboard. That causes a wrong value in the used energy because battery discharge and energie generated were cumulated. I would prefer using solar :-)

**Comment by Davvy80** [comment]
Can anyone help me, the first day was working fine now the flow doesn't move either, all [negative.. 
![screen](https://user-images.githubusercontent.com/130129774/232637083-e5c4bd75-f16e-4284-9630-7dbb6fb060cb.png)

**Comment by MontyPud** [comment]
Me too.  I'm also getting the previous days generation as a negative number at midnight the following day.
I got this far after following the kindly created youtube here. https://www.youtube.com/watch?v=OHvm-JgvQlg 
Also, thanks to @macxq for putting the effort into creating the integration.
I've no idea about what is possible in HA, having started about a week ago.
I don't suppose it is possible to do something like
if solar < 0
  solar = 0;
end;
? I suspect if it were that easy, you'd have done it already.

**Comment by koendruyts** [comment]
Is there already a fix for this issue preferably in the integration itself? I have the same issue...

**Comment by siobhanellis** [comment]
I also have this issue. It's not at midnight, but first read of the day (I found that out as HA was down for a few hours)

**Comment by mpr555** [comment]
Good morning all. Exactly the same for me.  New install of solar and batteries.  Anything I may be able to help with.  Please let me know.

**Comment by pdw-mb** [comment]
I have the same issue.  I think the fix is to change the state class for the relevant entity from `TOTAL` to `TOTAL_INCREASING`:

https://github.com/macxq/foxess-ha/blob/main/custom_components/foxess/sensor.py#L1469

From [here](https://developers.home-assistant.io/docs/core/entity/sensor/) :

> total_increasing	
> 
> Similar to total, with the restriction that the state represents a monotonically increasing positive total which periodically restarts counting from 0, e.g. a daily amount of consumed gas, weekly water consumption or lifetime energy consumption. Statistics of the accumulated growth of the sensor's value since it was first added is updated every 5 minutes. A decreasing value is interpreted as the start of a new meter cycle or the replacement of the meter.

**Comment by pdw-mb** [comment]
The above fix seems to work for me, so have raised a PR (#189).  It looks like all the other total entities were already set to `TOTAL_INCREASING`.
