### ISSUE TITLE
Error fetching data - last success 23.38 24th Feb 2023

### ISSUE THREAD

**Issue by rjhazeld** [macxq/foxess-ha#125]
My integration stopped working late on the 24th February after a couple of months working well . However, the Foxess app has continued to work. The HA log entries show:
**Unable to get Addressbook data from FoxESS Cloud
26 February 2023 at 02:39:33 – (ERROR) foxess (custom integration) - message first occurred at 25 February 2023 at 12:38:51 and shows up 9 times
Error fetching data: https://www.foxesscloud.com/c/v0/device/addressbook?deviceID=xxxxxxx failed with [Errno -3] Try again
26 February 2023 at 02:39:33 – (ERROR) RESTful - message first occurred at 25 February 2023 at 12:38:51 and shows up 9 times**

Looking at the Foxess App and Web portal more closely, the App appears to have some changes with one referring to 'charging pile equipment not connected yet'. The App and web page 'real data' seems to be a much shorter list. I wonder if they have made a change that has broken the data import.

Is this a general problem?

**Comment by rjhazeld** [comment]
The keys and values listed now on  on the web for my H1 inverter are:
Timezone Europe/London
Time 2023-03-01 19:23:04 GMT
SoC 20 %
RVolt 247.8 V
RPower -0.031 kW
RFreq 50.08 Hz
RCurrent 0.7 A
PVPower 0 kW
PV2Volt 6.2 V
PV2Power 0 kW
PV2Current 0 A
PV1Volt 7.3 V
PV1Power 0 kW
PV1Current 0 A
InvBatVolt 176.7 V
InvBatPower 0 kW
InvBatCurrent 0 A

**Comment by rjhazeld** [comment]
Seems the change is only for the H1-5.0-E  as the other inverter F5000 still seems to have the original key list.

**Comment by Instigater** [comment]
This error originated from a custom integration.

Logger: custom_components.foxess.sensor
Source: custom_components/foxess/sensor.py:143
Integration: foxess (documentation, issues)
First occurred: March 26, 2023 at 8:56:57 PM (155 occurrences)
Last logged: 9:52:02 AM

Unexpected error fetching FoxESS data: 'addressbook'
Unexpected error fetching FoxESS data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 143, in async_update_data
    if int(allData["addressbook"]["result"]["status"]) == 1 or int(allData["addressbook"]["result"]["status"]) == 2:
KeyError: 'addressbook'

**Comment by Instigater** [comment]
Managed to fix the issue. Appearently foxess-ha documentation isn't accurate enough. I fixed addressbook issue by enclosing configuration values in quotes like this:
`sensor:
  - platform: foxess
    username: "foxesscloud_username"
    password: "foxesscloud_password"
    deviceID: "foxesscloud_inverter_id"`

**Comment by rjhazeld** [comment]
Thanks, I have amended my configuration as suggested. However, it had started to work again about the 13th March. There was an HA Core update about then as well as FoxESS making changes to their cloud setup, I am not sure which fixed whatever the problem was. Apologies for not posting this earlier.  I hope that FoxESS leave the data structure alone and upgrade their 'cloud' to a reliable 24x7x365 operation.
