### ISSUE TITLE
Sensor with _power at the end of the name

### ISSUE THREAD

**Issue by tuliosilvajunior** [macxq/foxess-ha#13]
Hi all,
I'm not able to configure the Energy Dashboard due to some sensors that are working with "_power" at the name.
As you can see in the image below.
![image](https://user-images.githubusercontent.com/13374329/146370794-c9ed38a6-97dc-48b0-a10d-46c45c5e59ff.png)

Example: sensor.foxess_feedin doesn't have any energy info. But if I  verify the sensor.foxess_feedin_power I have all the right information coming from the Foxess Cloud.

**Comment by williamjeccles** [comment]
Hi @tuliosilvajunior, 

For example, if you set your "Return" energy property to use sensor.foxess_feedin you'll need to give it a day or so to start reporting.

If you're not seeing any fed in power back to the grid in your reports let me know as mine is working as expected.

**Comment by macxq** [comment]
@tuliosilvajunior  `Energy Dashboard `is using `Energy` measurement not `Power` :)  you ca read more about it here https://www.home-assistant.io/docs/energy/faq/

**Comment by tuliosilvajunior** [comment]
> Hi @tuliosilvajunior,
> 
> For example, if you set your "Return" energy property to use sensor.foxess_feedin you'll need to give it a day or so to start reporting.
> 
> If you're not seeing any fed in power back to the grid in your reports let me know as mine is working as expected.

Well, the funny part is the entities that are working are the entities with the _power at the end of the name.
But those entities are not available when I try to add them to the Energy Dashboard configuration as you can see in the image below.
![image](https://user-images.githubusercontent.com/13374329/146373157-8890ce9d-91ae-4632-9b26-184b0c5baa75.png)

**Comment by williamjeccles** [comment]
You set Grid Consumption and FeedIn as per my screenshot above, wait a few hours and it will start working.
