### ISSUE TITLE
How to round energy generated value? 

### ISSUE THREAD

**Issue by frcfrcfrc** [macxq/foxess-ha#134]
![image](https://user-images.githubusercontent.com/127096662/227157185-b6b28dba-a9bc-4183-a9a5-886038989d05.png)

**Comment by tomaskun** [comment]
It would be good if, when the inverter is offline at night, HA shows 0 instead of an unknown value..

**Comment by FozzieUK** [comment]
Home Assistant was updated a few releases back to allow display precision to be set by the user, click on the sensor you want to change, click on the cog in the top right corner of the information window, change the display precision as required, click update - all done.

**Comment by frcfrcfrc** [comment]
Thanks.
