### ISSUE TITLE
FoxESS not appearing in HACS integration list 

### ISSUE THREAD

**Issue by Sivivatu** [macxq/foxess-ha#135]
I'm trying to add the fox cloud to my HA vai HACS but it is not being found in the integration or frontend options
![Screenshot_20230325-182304.png](https://user-images.githubusercontent.com/7496456/227734902-4321e6cc-07e7-4847-bcda-902e6ed26778.png)

I have got HACS installed and it seems to think the repository is part of HACS but I can't add it to my environment.

![Screenshot_20230325-182313.png](https://user-images.githubusercontent.com/7496456/227734928-4000b78f-f82b-4926-ab23-6653e2487ac6.png)

Any help would be appreciated

**Comment by macxq** [comment]
you do not need to add this repository, it is already there you should use "Search for downloaded repository" functionality

**Comment by Sivivatu** [comment]
The first image is in the "Search downloaded repository", and the integration does not appear. Is there a way to refresh the addon lists or some other reason it would be missing?

**Comment by Sivivatu** [comment]
> you do not need to add this repository, it is already there you should use "Search for downloaded repository" functionality

The first image is in the "Search downloaded repository", and the integration does not appear. Is there a way to refresh the addon lists or some other reason it would be missing?

**Comment by Sivivatu** [comment]
Ok I found the issue, the hacs.json file filters the plugin to Norway.

Is there a reason for this limitation?

**Comment by macxq** [comment]
No, there is no reason for such limitation - it's just a mistake, it will be fixed with new release

**Comment by Sivivatu** [comment]
Brilliant thanks for the response

**Comment by macxq** [comment]
https://github.com/macxq/foxess-ha/releases/tag/v0.22 :)
