### ISSUE TITLE
New HA version, changes in RestData( encoding field has been added)

### ISSUE THREAD

**Issue by snaiperr** [macxq/foxess-ha#137]
In new HA version required to add encoding field in all RestData calls:
e.g.
`restAuth = RestData(hass = hass, method = METHOD_POST, resource = _ENDPOINT_AUTH, encoding = 'UTF-8', auth = None,
                        headers = headersAuth, params = None, data = payloadAuth, verify_ssl = DEFAULT_VERIFY_SSL)`

```
async def getAddresbook(hass, headersData, allData, deviceID,username, hashedPassword,tokenRefreshRetrys):
    restAddressBook = RestData(hass, METHOD_GET, _ENDPOINT_ADDRESSBOOK + deviceID, 'UTF-8', None, headersData, None, None, DEFAULT_VERIFY_SSL)
    await restAddressBook.async_update()

```

i have used 'UTF-8' it works, but not sure that it is correct value.

**Comment by snaiperr** [comment]
related to https://github.com/home-assistant/core/pull/90254
commit:  https://github.com/home-assistant/core/commit/1c465b5ad07e5b9ab589d50297899d2191af3308

**Comment by macxq** [comment]
https://github.com/macxq/foxess-ha/releases/tag/v0.24
