### ISSUE TITLE
Update Speed ist to slow...

### ISSUE THREAD

**Issue by muhkuh666** [macxq/foxess-ha#150]
I will get updates at around 17 minutes between HASS and Foxess.... how can this be optimised?

**Comment by macxq** [comment]
@muhkuh666 is https://www.foxesscloud.com/ up to date and has more fresh data for your installation ? 
Please enable debug logs and validate what data are returned from API

**Comment by brunofcat** [comment]
Hi,

Try to adjust the file sensor.py
line 90 SCAN_INTERVAL = timedelta(minutes=5)

if you set timedelta(seconds=15) it will be faster than the portal (it's my case) :D

**Comment by mschae** [comment]
I’m seeing the same issue unfortunately. Resolution for most sensors is 1hr. I realize the datalogger only sends data every five minutes but that would be vastly superior to one hour…

**Comment by mschae** [comment]
@macxq any chance you could take a look?
