### ISSUE TITLE
missing 1 required positional argument: 'ssl_cipher_list'

### ISSUE THREAD

**Issue by lukaszgithub** [macxq/foxess-ha#165]
**Describe the bug**
integration doesn't connect to ess service ->
missing 1 required positional argument: 'ssl_cipher_list' 

**To Reproduce**
after ha update to 2023.5.0

**Expected behavior**
no data

**Debug logs:**
Unexpected error fetching FoxESS data: RestData.__init__() missing 1 required positional argument: 'ssl_cipher_list'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 217, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 125, in async_update_data
    token = await authAndgetToken(hass, username, hashedPassword)
  File "/config/custom_components/foxess/sensor.py", line 242, in authAndgetToken
    restAuth = RestData(hass, METHOD_POST, _ENDPOINT_AUTH, DEFAULT_ENCODING,  None,
TypeError: RestData.__init__() missing 1 required positional argument: 'ssl_cipher_list'

**HA version:**
2023.5.0

**foxess-ha version:**
0.25

**Comment by FraWi1963** [comment]
Same here...

**Comment by baczus** [comment]
As a workaround, you can modify sensor.py file:

1. Add new import

`from homeassistant.util.ssl import SSLCipherList`

3. Add an additional parameter to each function RestData `SSLCipherList.PYTHON_DEFAULT`  e.g.

`RestData(hass, METHOD_GET, _ENDPOINT_ADDRESSBOOK +
                               deviceID, DEFAULT_ENCODING,  None, headersData, None, None, DEFAULT_VERIFY_SSL)`
should look like this:
`RestData(hass, METHOD_GET, _ENDPOINT_ADDRESSBOOK +
                               deviceID, DEFAULT_ENCODING,  None, headersData, None, None, DEFAULT_VERIFY_SSL, SSLCipherList.PYTHON_DEFAULT)

**Comment by alexmercerscott** [comment]
Same issue here after updating to Home Assistant 2023.5.0

Hopefully the fix above by @baczus works, and can be implemented in the official release. Just adding to the thread to keep traction on the issue.

**Comment by pediatragliwice** [comment]
@baczus  can you create PR for that ?

**Comment by macxq** [comment]
@baczus  can you create PR for that ?

**Comment by baczus** [comment]
Sure, https://github.com/macxq/foxess-ha/pull/166
