### ISSUE TITLE
Unable to pick sensor.foxess_solar_power for Solar production in Energy dashboard

### ISSUE THREAD

**Issue by nikowitt** [macxq/foxess-ha#167]
Hi there,
thanks in advance for this great piece of software! I am currently setting up my HA instance and wanted to add "Solar production" to my Energy Dashboard. From the metrics, I see that sensor.foxess_solar_power would be the correct sensor, but I can only add sensor.foxess_solar which returns nothing in my case. In this case, HA advises me to point out https://www.home-assistant.io/more-info/statistics/.

Is there anything I am doing wrong?

**Comment by Daibutt** [comment]
I don't currently have this integration so not totally sure what the sensors names are now, but the built in HA energy dashboard uses energy (kWh) data not power (kW).
foxess_solar_power (kW) will not work. 
You will need something that is called solar_energy or energy_solar or solar_generated or something like that (units in kWh)

**Comment by nikowitt** [comment]
Guess I simply overlooked that one
https://github.com/macxq/foxess-ha/wiki/How-to-fix-Energy-Dashboard-data-(statistic-data) ;)
