### ISSUE TITLE
Cannot use solar sensor as SOLAR PRODUCTION sensor in Energy dashboard

### ISSUE THREAD

**Issue by benek984** [macxq/foxess-ha#18]
Hello, I have below added to my configuration:

platform: integration
source: sensor.foxess_pv1_power
name: pv1_sum
unit_time: h
round: 2

I can see the value but I am not able to add this sensor as Solar Panel (source) under Energy configuration. It just doesn't appears when searching in Configuration -> Energy ->  Solar Panels -> ADD SOLAR PRODUCTION

**Comment by davidmul87** [comment]
I have the same issue. Any ideas or did you manage to solve if @benek984 ?

**Comment by benek984** [comment]
@davidmul87 no, problem still exist. Looks no one has advised the solution yet.

**Comment by davidmul87** [comment]
Hi @benek984 - I managed to get it working. Once my system had been generating solar data I was able to then add the pv1_sum to my energy dashboard. Where do you have it in your configuration? I put that code under 'sensor' but as I say it only started working once there was data feeding through. 

The last few days however I have found the API to be very unstable.

**Comment by benek984** [comment]
Hi,

I have my configuration.yaml spliced into separated files:
<img width="992" alt="Studio_Code_Server_-_Home_Assistant-2" src="https://user-images.githubusercontent.com/62546477/149019013-4e7a8940-613a-4fb2-bee9-ed9b91ea0753.png">

then:

in sensors.yaml

<img width="1039" alt="Studio_Code_Server_-_Home_Assistant" src="https://user-images.githubusercontent.com/62546477/149019081-9c41f69e-0501-4e37-a1cd-7440012fcafc.png">


in entities I can see data in this sensor:


<img width="1158" alt="Screenshot_11_01_2022__20_27" src="https://user-images.githubusercontent.com/62546477/149019190-bf235c30-2157-4664-8000-4535cb9a5bff.png">


but in Energy config I can't see this sensor:

<img width="433" alt="Screenshot_11_01_2022__20_45" src="https://user-images.githubusercontent.com/62546477/149019280-5cec58c8-d72f-4990-9bd2-151eba8a08e0.png">

**Comment by davidmul87** [comment]
Are you on the latest version of HA? I know that in the initial instances of the energy dashboard it was quite picky about the set up of sensors and needing to have a last reset datapoint. I believe this was later changed but if you're not on the latest version may still be an issue. 

All I know is that mine is now working fine with basically the same setup.

**Comment by davidmul87** [comment]
PS - one other thing to check / try is to make sure that the entity has received data each time you reset your HA. If it hasn't received data yet then i think the sensor won't be fully or properly configured yet.

**Comment by macxq** [comment]
@benek984 do you have such/similar entries in your logs:

```
2022-01-12 08:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.pv1_sum has unit None which is unsupported for device_class energy
2022-01-12 08:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The normalized unit of sensor.pv1_sum (kWh) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
```

**Comment by benek984** [comment]
@macxq yes I have this logs in my HA

""""
2022-01-12 08:10:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The normalized unit of sensor.pv1_sum (kWh) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2022-01-12 08:10:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The normalized unit of sensor.daily_pv1_sum (kWh) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None

'''''

What is the solution in this case?

**Comment by benek984** [comment]
> Are you on the latest version of HA? I know that in the initial instances of the energy dashboard it was quite picky about the set up of sensors and needing to have a last reset datapoint. I believe this was later changed but if you're not on the latest version may still be an issue.
> 
> All I know is that mine is now working fine with basically the same setup.

Hi, I am on the latest HA version

**Comment by macxq** [comment]
@benek984 https://github.com/home-assistant/core/issues/61795#issuecomment-996206679 this should work ;) 

please, close the ticket if this will help.

**Comment by benek984** [comment]
> @benek984 [home-assistant/core#61795 (comment)](https://github.com/home-assistant/core/issues/61795#issuecomment-996206679) this should work ;)
> 
> please, close the ticket if this will help.

This works so closing the issue
