### ISSUE TITLE
HA Energy Dashboard "FoxESS - Solar Power" not available in Solar drop down

### ISSUE THREAD

**Issue by mpr555** [macxq/foxess-ha#183]
**Describe the bug**
With in HA Energy dashboard where it asks you to put Solar production.  It only allows you to pick "FoxESS - Solar" which I think is the total power for the day.  I believe the one in the drop-down needs to be "FoxESS - Solar Power" but It is not listed in the view.

**To Reproduce**
In HA go to Settings dashboard -> Energy and edit
select solar.  In the drop-down, the FoxESS - Solar Power is not present.
If I go to the overview and add a card I can add FoxESS - Solar Power

**Expected behaviour**
Be able to select FoxESS - Solar Power in the solar panel drop-down in the energy dashboard

**Screenshots**

**Debug logs:**

**HA version:**
Home Assistant 2023.6.3
Supervisor 2023.06.2
Operating System 10.3
Frontend 20230608.0 - latest

**foxess-ha version:**
V 0.26

**Comment by Daibutt** [comment]
Pretty sure everything in the Energy dashboard should be energy (kWh) not power (kW), that's why Solar Power doesn't show up.
The dashboard looks at hourly increments of the total daily solar to create the charts.

**Comment by Daibutt** [comment]
![image](https://github.com/macxq/foxess-ha/assets/69276073/c852f7e6-745c-4955-9a07-99919bed2c31)

**Comment by mpr555** [comment]
> Pretty sure everything in the Energy dashboard should be energy (kWh) not power (kW), that's why Solar Power doesn't show up. The dashboard looks at hourly increments of the total daily solar to create the charts.

Thank for for the reply.  FoxESS - Solar seems to be the total generated for that day.  Could you please guide my on which is the best option for this?

**Comment by Daibutt** [comment]
Yep, that should work. It should start the day at zero and gradually count up. The dashboard **looks at hourly increments** of that sensor. 
For example, I use my absolute elec and gas meter readings (as displayed on thh supplier meters) in my dashboard, and as dashboard is only looking at the difference between one hour and the next it works fine.

All the sensors in the built-in HA Energy Dashboard should be kWh (or Wh...) not power kW.

**Comment by mpr555** [comment]
@Daibutt - I shall try again, but at the end of the day on the Energy distribution entity solar was saying 8kWh and mine can only produce 5 tops.  so was confused.  maybe it was displaying it incorrectly.

I have changed them to daily_pv1_sum & daily_pv2_sum as I have front and back, and that seems to be correct with what I get from the FoxCloud dashboard.  Or is that incorrect as well?

**Comment by mpr555** [comment]
@Daibutt - I think some historical data is skewing my display.  I'll leave it for a couple of days and see.

**Comment by Daibutt** [comment]
Yeah pv1/pv2 sum should work. That's what I use but from a different HA
integration.
Think you might be mixing up power and energy. When you say you can produce
5 tops, that's presumably your instantaneous solar capacity of 5kW power.
If you produce say 2kW for 4 hrs, you will have made 8kWh energy.

https://www.power-sonic.com/blog/kw-vs-kwh-explained/

**Comment by mpr555** [comment]
@Daibutt - I really appreciate you getting back to me and I am now getting what you are saying.  I think I had some bad data in, so I basically rebuilt the HA server and started again.  Thanks for the link as well.  Hopefully, this will be getting the right data in now.

**Comment by Daibutt** [comment]
👍
