### ISSUE TITLE
[FEAUTRE REQUEST] More Stats - Battery, Force Charge, Export to Grid etc.

### ISSUE THREAD

**Issue by BigManDave** [macxq/foxess-ha#2]
Good Morning,

Thanks for the work you've put in so far. I was wondering what are the chances on being able to get more info out of this integration?
My configuration is solar and battery with force charge and export to grid. So I'd be hoping to get things like Production (kwh), Battery charge (kwh), battery discharge (kwh), grid usage (kwh), grid export (kwh), energy draw (kwh), battery SoC (%), I think.

I'm not a developer but I've had a poke around the API and can see that there are a lot of variables available. The list can be seen using GET https://www.foxesscloud.com/c/v1/device/variables?deviceID=[xxxxx].
However I can only see that these are usable with a POST and a date range. I think there's a limit on how many can be in each POST too.

Would love to hear your feedback. Thanks in advance.

**Comment by macxq** [comment]
I will investigate what the api allows us and if possible I will implements this!

**Comment by BigManDave** [comment]
![Screenshot_20211030-004536.jpg](https://user-images.githubusercontent.com/66840216/139512073-44f3e673-77c9-4ea5-8d0c-46cc26e2e46c.jpg)
Decided to stay up to make sure my forced charge from grid was working. See negative generation power that I've been referring to. Looks like it might not even affect generation energy since it's at zero. Unless the negative subtracts from whatever value was already there, not sure.

**Comment by Daibutt** [comment]
@BigManDave Yes you are right, the generated energy figure does not go negative. Energy values (kWh) are what is required for the energy dashboard, not power.
The accumulated energy sensor values do seem to come from FoxCloud. I think if they were accumulated in HA they would update every sensor scan, and have multiple decimal places. They actually only increase by 0.1 increments (same as FoxCloud values) and only update when the value increases by 0.1.

@macxq I have had a think about the solar generation calculation.
Either the Riemann sum of pv1power + pv2 power as mentioned earlier and/or ...

Energy balance: In - Out = Accumulation
(Solar generation + Grid consumption) - (loads consumption) = (battery charge - battery discharge)
or rewritten as;
Solar Generation = battery charge - battery discharge - Grid consumption + loads consumption.
I'm not sure if the loads consumption energy kWh is available in the API though?

**Comment by macxq** [comment]
@BigManDave @Daibutt these all measurements goes directly for FoxCloud :)  I'm just fetching them and saving to HA. The negative  `Generation Power` is what you can also observe in your foxesscloud instance:

![Screenshot 2021-11-01 at 09 50 50](https://user-images.githubusercontent.com/2965092/139646278-437cc160-a2a6-4e27-be01-a467ed6909ec.png)

There is a lot of comment for you both i appreciate it but I'm sinking in them to have conclusions :) 
1. Does` Energy Generated ` match what you see in foxesscloud as `Today Yield` ? 
2. Is foxesscloud correctly calculating `Today Yield`?
3. Is `Today Yield ` the same as you are refering to `Solar Generation`?

**Comment by Daibutt** [comment]
@macxq Apologies for the many comments!
In answer to your questions;

1) I have only had FoxESS-HA running for two complete days. One of those days Total Yield matched Energy Generated, and the other day it did not - but we changed clocks from daylight savings time, so maybe that screwed the numbers a little?

2)  Possibly - but I'm not sure it is useful! See answer 3

3) Today yield is not the same as what I am callling solar generation;
For Today Yield/Energy Generated, it seems FoxCloud draws the "boundary" of the PV system around the panels, batteries & inverter ;
![image](https://user-images.githubusercontent.com/69276073/139651976-12fbf73b-93fb-49cc-90ff-2ea9adc40955.png)

As end users, we are likley more interested in understanding output of PV arrays, and our "boundary" is like this;
![image](https://user-images.githubusercontent.com/69276073/139652256-a1291ba9-99f1-4a02-97e0-c1888d39cf66.png)

As far as I can tell, that **energy** figure is not available on FoxCloud (kWh daily accumulated energy from PV arrays). 
But the real time PV power figures are available though, as pv1power, pv2power or pvPower;

![image](https://user-images.githubusercontent.com/69276073/139652736-fc0e5966-37d1-4f2a-b6e5-b241c138825b.png)

![image](https://user-images.githubusercontent.com/69276073/139652656-3caeff13-343c-4d42-b08f-a3388a71eed0.png)


I hope this helps!

**Comment by macxq** [comment]
Now I get it  and see it, let me think on it!

**Comment by Daibutt** [comment]
@macxq If it is not possible to integrate/accumulate pv1Power, pv2Power, pvPower to get solar generation in kWh, the other idea I mentioned was doing an energy balance to infer solar generated energy kWh.
Add the green arrows and subtract the red ones in this picture.
![image](https://user-images.githubusercontent.com/69276073/139824547-e6920ad5-f66f-4a22-8824-a5b951cfe5ee.png)

Obviously this needs an energy value for loads consumption, which I think is availble on the FoxCloud overview/statistics diagram as Load Yield
![image](https://user-images.githubusercontent.com/69276073/139824846-2e144199-9976-4e7a-9ed9-d5e0b95a4da7.png)

This won't give exactly the same as integrating the pvPower method because of inverter losses but will be close.

**Comment by macxq** [comment]
@Daibutt i have implemented fetching `Load` and `Load Power` but i cannot test it because my instance does not have battery and does not report any value under this.


it is on the main branch so you need to:

```
git checkout main
git pull
```

**Comment by Daibutt** [comment]
@macxq Fantastic!
New entities working;
![image](https://user-images.githubusercontent.com/69276073/139889727-deaffbe7-bba7-4674-94a3-d72f3071c9f2.png)

And match FoxCloud;
![image](https://user-images.githubusercontent.com/69276073/139890497-60d5dafe-c1d1-49c9-9982-5c7bf7fb2a9d.png)

![image](https://user-images.githubusercontent.com/69276073/139890932-5800f98b-1957-435e-b7b8-0fb3d48e5f2d.png)

So now you have all values for my green and red arrows!
Green:
![image](https://user-images.githubusercontent.com/69276073/139893763-b176a27d-f908-456e-9d4b-08dcc8cfa8b0.png)
Red:
![image](https://user-images.githubusercontent.com/69276073/139894151-ca91f102-3eec-4888-8491-389a5bd1a614.png)


Can you make a new Solar Generation energy entity by adding and subtracting these?

**Comment by macxq** [comment]
@Daibutt done 👍  

check out how it looks for you, because for me (i do not have battery) data looks wrong ;) 
<img width="466" alt="Screenshot 2021-11-02 at 19 27 08" src="https://user-images.githubusercontent.com/2965092/139923809-ba13e52b-591b-4d5a-a737-a5ce3d265167.png">

probably the is needed some logic to distinction two two types of installation

**Comment by Daibutt** [comment]
Hi @macxq 
OK, so I gave this a try, maybe I did it wrong, I'm not very good at this stuff!
This is what I did;
![image](https://user-images.githubusercontent.com/69276073/139961421-c43380e1-88bf-4540-8609-78fd8eb87600.png)

Then restarted HA server.

I do not see the new solar entities.
![image](https://user-images.githubusercontent.com/69276073/139961729-0acebd01-edd2-491c-bfba-2207764d655f.png)

Should I reclone the whole foxess-ha thing?

**Comment by Daibutt** [comment]
> 
> 
> @Daibutt done 👍
> 
> check out how it looks for you, because for me (i do not have battery) data looks wrong ;) <img alt="Screenshot 2021-11-02 at 19 27 08" width="466" src="https://user-images.githubusercontent.com/2965092/139923809-ba13e52b-591b-4d5a-a737-a5ce3d265167.png">
> 
> probably the is needed some logic to distinction two two types of installation

@macxq Loadpower for me at end of today looked correct. 11.5 kWh and my last 2 month daily average is 11.3kWh.

**Comment by macxq** [comment]
@Daibutt I did not pushed all the things to repo 🤦‍♂️  
Please do `git pull` one more time and the new sensor should apperen

**Comment by Daibutt** [comment]
@macxq Both new solar entities now working :)

Numbers make sense for me so far today;
Grid Consumption + Battery Discharge = 7.9kWh
Batttery Charge + Loads = 7.9 kWh    (Feed In=0)
Solar Generation = 0 kWh
This makes sense as sun is only just hitting PV array.

Solar Power entity currently showing 0.16kW which ties up pretty well with current Solcast forecast.
Will update later today after I've generated some PV  energy!

**Comment by BigManDave** [comment]
@Daibutt Yep I'm seeing similar to you. Number mostly making sense apart from the negatives I think. 
Would also love to see SoC and ideally battery temp too, just to be aware of how hot it gets in the loft! 🙂
@macxq as always fantastic work here, really, really appreciate it.

**Comment by Daibutt** [comment]
@BigManDave @macxq Glad it's working for you too Dave. I think the way it's calculated any system losses end up in the solar generated number, as everthing else is measured. But I'll have a think about that!!
BTW, if the temp in my living room in South Wales is anything to go by, your loft in Yorkshire is going to be pretty cool at the moment :)

**Comment by Daibutt** [comment]
@macxq @BigManDave I'm importing as we speak. Solar power is showing -ve (-170W). 
This seems representative  of when I am charging battery. I import 5kW & battery charges at 4.8kW. I know this is more work but is there any way to feed -ve solar values to an " inverter losses" entity? This would tidy up the numbers and also give us a measure of inverter losses.? Just a thought :) and I'm not the guy  that's got to code it :stuck_out_tongue_winking_eye:

**Comment by BigManDave** [comment]
@macxq @Daibutt So with the negative solar values it looks like it's making HA wait until the Solar Energy is positive before it will begin plotting anything on the graph. I.e. Inverter losses overnight mean by the time the sun rises I've got -1kwh to make up before I'll get any production on the graph.
I guess reporting-wise it's not actually that bad, since it means the generated solar energy reflects the actual AC energy you're getting out of the solar system. Just a shame it means less pretty graphs!

I've been working on grabbing SoC and BatTemp. Hopefully I'll have a pull request ready later for review, if that's ok :)

**Comment by Daibutt** [comment]
@macxq @BigManDave Sorry to be a bit of a noob... I see that there is an update with SoC & bat temp. It is with HACS? 
I'm not even sure I know what that is or if I have HACS? Can I still do the github clone/pull stuff to get the new entities?

**Comment by Daibutt** [comment]
@macxq @BigManDave Fantastic work guys! Love the update. I didn't have/use HACS previously so this forced me to do a bit of reading and get it installed!
The SoC & battery temp entities are welcome additions. Would it also be possible to add pv1Power & pv2Power entities please? It would be useful for understanding performance of each array.

**Comment by macxq** [comment]
@Daibutt yes, it wold be :) 
more sensors we have, more I think some   some configuration around this is required to menage the haos :) not everyone will interesting in all the sensors especially if have small installation without battery

**Comment by Daibutt** [comment]
Hi @macxq, spotted the new beta version with PV1-4 sensors, so I installed that 👍, nice work.
It looked like it was working great, values increasing as sun moved round.
But when it became cloudy & solar reduced, the values "froze".
![image](https://user-images.githubusercontent.com/69276073/140926246-0b2a3f8d-79bf-48b5-a3a0-4ebf0d40fcbc.png)

Looking at the values, could it be they are picking the max values from this chart, rather than the latest/real time (lower) values?
![image](https://user-images.githubusercontent.com/69276073/140926137-8d5831fb-7472-44f5-9ee1-f3c4089a9121.png)

**Comment by macxq** [comment]
@Daibutt  I have got the same - need to validate that 
<img width="387" alt="Screenshot 2021-11-09 at 20 59 10" src="https://user-images.githubusercontent.com/2965092/140995877-47414cd3-a88a-43af-add4-3736e197337e.png">

**Comment by macxq** [comment]
@Daibutt with the [v0.9.2-beta](https://github.com/macxq/foxess-ha/releases/tag/v0.9.2-beta) it should be fixed

**Comment by Daibutt** [comment]
@macxq this seems to be working great 👍 
I created Riemann sum integrals for my PV1 & PV2 and now feed these into the HA energy dashboard (instead of sensor.foxess_solar).
This gets round the problem with the energy balance method sometimes throwing out negative values.
I'm guessing inverter losses will now end up assigned to "Home" by the dashboard....
It also means you can assign Forecast.Solar predictions to each array and get 2 prediction lines in the dashboard.

![image](https://user-images.githubusercontent.com/69276073/141095680-1e1a48d8-fc89-4594-959d-ae5395b63f00.png)

> - platform: integration
  source: sensor.foxess_pv1_power
  name: pv1_sum
  unit_time: h
  round: 2

> - platform: integration
  source: sensor.foxess_pv2_power
  name: pv2_sum
  unit_time: h
  round: 2

Really great work. Thank you!

**Comment by BigManDave** [comment]
@Daibutt I've followed your comment to get those sensors set up. It looks like it didn't reset overnight. Did you figure that bit out?
Thanks in advance 🙂

**Comment by Daibutt** [comment]
@BigManDave those sensors will carry on accumulating forever which is OK for input to HA energy dashboard, the same as the inputs for gas & import/export elec meters.

If you want a daily sum outside of the HA dashboard add them as utility meters, sourced from the ones you just set up;

utility_meter:
   daily_pv1_sum:
    source: sensor.pv1_sum
    cycle: daily
    
  daily_pv2_sum:
    source: sensor.pv2_sum
    cycle: daily
 
This should work.

**Comment by BigManDave** [comment]
@Daibutt Thanks! I hadn't confgiured them in the dashboard yet, wanted to verify the values looked right first so didn't realise it'd work without reset. Thanks for the utility meter config too :)

**Comment by Daibutt** [comment]
@BigManDave If it's any use for you too, I added a couple of template sensors to get the real time PV total and the daily PV total;

- platform: template
  sensors:
    pv_total_daily:
      friendly_name: "Daily sum of PV1 + PV2"
      value_template: "{{ states('sensor.daily_pv1_sum') | float + states('sensor.daily_pv2_sum') | float }}"
      unit_of_measurement: "kWh"
      
 
- platform: template
  sensors:
    pv_total:
      friendly_name: "Sum of PV1 + PV2"
      value_template: "{{ states('sensor.foxess_pv1_power') | float + states('sensor.foxess_pv2_power') | float }}"
      unit_of_measurement: "kW"

**Comment by macxq** [comment]
@Daibutt @BigManDave  awesome work 💪  I'm going to close this issue but wondering if you wold like to document your awesome work around energy generation per string as a wiki article  - after closing this issue it will be hard to reach here, i think what you did is valuable for the other users 🤓

**Comment by Daibutt** [comment]
@macxq Yes no problem putting some stuff in a Wiki. I've never created a Github Wiki before. 
Looking at the instructions I don't seem to have the option to add a new page;
![image](https://user-images.githubusercontent.com/69276073/142196880-671b65af-4aba-4cc0-85fb-35c9a7b6d3c7.png)

**Comment by macxq** [comment]
@Daibutt  I have added you as a collaborator you can add wiki pages tight now ;)

**Comment by Daibutt** [comment]
@macxq  Thanks. I have had a go at creating my first Wiki page! The formatting was a bit of a nightmare, but I got something in there! Appreaciate any feedback. 
@BigManDave, any feedback from you very welcome too.

**Comment by macxq** [comment]
Thank you 🙇‍♂️ i have fixed the formatting a bit ;)

**Comment by Daibutt** [comment]
Hi @macxq 
When you get 5 minutes could you update the readme with current entities please?
It doesnt include the solar, solar_power, PV1, PV2 etc ones 
![image](https://user-images.githubusercontent.com/69276073/145122858-f845cce3-5fae-4688-8bff-061d904b5f6a.png)

Thanks ;)

**Comment by macxq** [comment]
@Daibutt yes I will do this! thx for bringing this up ;)

**Comment by macxq** [comment]
@Daibutt doc updated - feel free to add comments to PR https://github.com/macxq/foxess-ha/pull/16

**Comment by Daibutt** [comment]
Looks good @macxq :)
