### ISSUE TITLE
Entity not available

### ISSUE THREAD

**Issue by AndaleR** [macxq/foxess-ha#212]
Hi there from Germany!

New to Home-Assistant, new to GitHub - but I try to give the informations you need.

I have installed HA this weekend, just to get the data from Foxess-Inverter and battery.

**Screenshots**
<img width="345" alt="image" src="https://github.com/macxq/foxess-ha/assets/156580878/765845fd-9b73-40cf-8a21-50aa16f44e4b">
<img width="349" alt="image" src="https://github.com/macxq/foxess-ha/assets/156580878/f9f72a44-bf96-4d8e-918d-fc8abc67f012">

How can I fix this? I installed it with HACS, not manually - wanted to go the easy way. But should be the same result in both ways?

**HA version:**
2024.1.3

**foxess-ha version:**
0.32

**Comment by FozzieUK** [comment]
Hi can you confirm whether this is still happening, or is it now working (the FoxESS cloud has been particularly unreliable these last few weeks).

It would be useful if you could post any logs that relate to this, you can find them in System, Logs - then click 'Load Full Logs' at the bottom - if you could cut and paste any logs that contain the header 'custom_components.foxess.sensor' please

**Comment by syberx** [comment]
same ... : Unexpected error fetching FoxESS data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 269, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/foxess/sensor.py", line 125, in async_update_data
    token = await authAndgetToken(hass, username, hashedPassword)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/foxess/sensor.py", line 251, in authAndgetToken
    response = json.loads(restAuth.data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by FozzieUK** [comment]
Please see https://github.com/macxq/foxess-ha/issues/177#issuecomment-1953784005

We are waiting on FoxESS for an update
