### ISSUE TITLE
Username/PW failure

### ISSUE THREAD

**Issue by BenjaminKoyen** [macxq/foxess-ha#216]
Hi,

I've downloaded the FoxEss repository from HACS and added the code to configuration.yaml.
After restarting I get the below error:

Logger: custom_components.foxess.sensor
Source: helpers/update_coordinator.py:332
Integration: foxess ([documentation](https://github.com/macxq/foxess-ha), [issues](https://github.com/macxq/foxess-ha/issues))
First occurred: 21:30:57 (1 occurrences)
Last logged: 21:30:57
Error fetching FoxESS data: Unable to login to FoxESS Cloud - bad username or password! {"errno":41807,"result":null}

Seems obvious -- something with username & password. However, I used the exact same username and pw as I am logging into the foxcloud directly at the same moment. 
Any suggestions what could be wrong? 

sensor:
  - platform: foxess
    name: FoxEss1
    username: foxesscloud_xxx
    password: foxesscloud_xxx
    deviceID: foxesscloud_c82393f3-7475-4f6b-ac86-xxxxxxx

Quite new to all of this, probably something stupid that went wrong :)

Benjamin

**Comment by FozzieUK** [comment]
‘41807’ is definitely an incorrect username or password error, it is case specific so whatever the case you use to log into the Foxesscloud should be precisely copied.

Unless you have multiple inverters I would recommend you remove the line ‘name: FoxEss1’ from the platform config.

I’m sure it’s just a copy thing in your text above, but platform should have a ‘-‘ in front of it
```
- platform:
  username: foxess username
  password: foxess_password
  deviceID: c82393f3-7475-4f6b-ac86-xxxxxxxxxxx
```

**Comment by BenjaminKoyen** [comment]
I have the - in front, its a copy-paste thing indeed. 
I've done pw reset, checked all the writing etc. but still gives same error.
I removed the name part (did not have it before, but read it somewhere as a fix). 

sensor:
  - platform: foxess
    username: foxesscloud_xxxxxx
    password: foxesscloud_ResetDone
    deviceID: foxesscloud_c82393f3-7475-4f6b-ac86-xxxxxxx

Any other suggestions or stupidities that I could have missed? 


For info: I'm getting two errors, same second, so not sure if one is causing the other?

FoxESS Cloud initializaction failed, fix error and restar ha
17:46:01 – (FOUT) foxess (aangepaste integratie)
Error fetching FoxESS data: Unable to login to FoxESS Cloud - bad username or password! {"errno":41807,"result":null}
17:46:01 – (FOUT) foxess (aangepaste integratie)

**Comment by FozzieUK** [comment]
the second error 'fix error and restart' is just a result of the first error - so it has to be something to do with your username / password combo or the deviceID.

Just to be sure you are entering it correctly, as an example

my_username = "Freddy42"
my_password = "FredsPass"
my_deviceID = c82393f3-7475-4f6b-ac86-123456789012

So the platform entry would be (no quotes etc..) :
```
  - platform: foxess
    username: Freddy42
    password: FredsPass
    deviceID: c82393f3-7475-4f6b-ac86-123456789012
```

**Comment by Daibutt** [comment]
This probably isn't much help but ...... I vaguely remember (quite some time ago) someone having login issues and it seemed to be their username or password had characters in it that didn't work. Something like & % $ # ~ " ! \ was the issue.
Just an idea :)

**Comment by BenjaminKoyen** [comment]
I knew it would be a newbie mistake, but found it thanks to the comments!
I was configuring your example as:
 
 - platform: foxess
    username: foxesscloud_Freddy42
    password: foxesscloud_FredsPass
    deviceID: foxesscloud_c82393f3-7475-4f6b-ac86-123456789012

Removed the foxesscloud, seems to work now, can start playing with it :). 
Thanks for the feedbacks reaching out to stupid mistakes!

**Comment by FozzieUK** [comment]
@Daibutt Thanks Dave, I was starting to think that way myself 😊 

@BenjaminKoyen no problem, I did wonder as you kept inserting the foxesscloud name, i'll change the readme to make it clearer - glad you got it sorted out 👍

**Comment by Mitchel85** [comment]
> This probably isn't much help but ...... I vaguely remember (quite some time ago) someone having login issues and it seemed to be their username or password had characters in it that didn't work. Something like & % $ # ~ " ! \ was the issue. Just an idea :)

That's it! Had issues exactly because of that. Btw not even a "." is allowed.

**Comment by FozzieUK** [comment]
@Mitchel85 thanks for that, on another post the user found a password with '!' in it wouldn't work either.

The better news is that the forthcoming openAPI version of this integration uses a personal_api_key (a bit like the deviceID) and not the username / password combo to get data so that will be fixed going forwards - i'm just waiting on FoxESS to confirm a few changes in the openAPI and that version can be released, hopefully towards the end of this month.

**Comment by Mitchel85** [comment]
> @Mitchel85 thanks for that, on another post the user found a password with '!' in it wouldn't work either.
> 
> The better news is that the forthcoming openAPI version of this integration uses a personal_api_key (a bit like the deviceID) and not the username / password combo to get data so that will be fixed going forwards - i'm just waiting on FoxESS to confirm a few changes in the openAPI and that version can be released, hopefully towards the end of this month.

Yes and no. New API Integration does work, but some sensors arent availabele f.e. SoC. just switched to old fox repository

**Comment by FozzieUK** [comment]
@Mitchel85 

That's interesting, is it just SoC that didn't work or are there any others ?

I'm wondering if the new api has changed your entity name? - my test system is reporting battery SoC and the entity is named sensor.foxess_bat_soc - can you tell me what your entity name is on the old cloud api please ?

The old api will be made private at some point in the (near) future so it has to work on the openAPI - if you have the time it would be really helpful if you could do some testing and post any errors from your logs please.

**Comment by Mitchel85** [comment]
@FozzieUK 
Due to your answer, I assumed SoC sensor should have work, so I decided to reinstall Foxesscloud Api... and surpise, all sensors work, also SoC. Thx you for that hint.

**Comment by FozzieUK** [comment]
@Mitchel85 That's great, thanks 👍
