### ISSUE TITLE
All entities no longer being provided by foxxess integration

### ISSUE THREAD

**Issue by chesterflaps** [macxq/foxess-ha#229]
**Describe the bug**
For the past few weeks I have noticed none of the sensors are working. See attached screenshot.

I have looked into it already to try and wort it and found that there was a change in the api recently. I found that I needed to add to the bottom of the sensor in the config file, the serial number of the inverter and the api key which I have generated from the FOXESS cloud portal.

I have 2 inverters do I used the same api key for both. Not sure if that is correct but I cannot generate more than one api key as it says it will delete the old one if I do.

``
sensor:
  - platform: foxess
    name: FoxESS1
    username: ******
    password: *****
    deviceID: 59e48e7c-95ff-*****
    deviceSN: *******
    apikey: e6aaa0d4-********
  - platform: foxess
    name: FoxESS2
    username: *****
    password: *****
    deviceID: b9d1760b-68*****
    deviceSN: *******
    apikey: e6aaa0d4-******same as above
``

**Expected behavior**
I would expect to be able to see that the sensors are working

**Screenshots**
See attached.

**Debug logs:**
LOGGER.error(
            "FoxESS Cloud initialisation failed, Fatal Error - correct error and restart Home Assistant")
        return False

    async_add_entities([
        FoxESSPV1Current(coordinator, name, deviceID),
        FoxESSPV1Power(coordinator, name, deviceID),
        FoxESSPV1Volt(coordinator, name, deviceID),
        FoxESSPV2Current(coordinator, name, deviceID),
        FoxESSPV2Power(coordinator, name, deviceID),
        FoxESSPV2Volt(coordinator, name, deviceID),
        FoxESSPV3Current(coordinator, name, deviceID),
        FoxESSPV3Power(coordinator, name, deviceID),
        FoxESSPV3Volt(coordinator, name, deviceID),
        FoxESSPV4Current(coordinator, name, deviceID),
        FoxESSPV4Power(coordinator, name, deviceID),
        FoxESSPV4Volt(coordinator, name, deviceID),
        FoxESSPVPower(coordinator, name, deviceID),
        FoxESSRCurrent(coordinator, name, deviceID),
        FoxESSRFreq(coordinator, name, deviceID),
        FoxESSRPower(coordinator, name, deviceID),
        FoxESSMeter2Power(coordinator, name, deviceID),
        FoxESSRVolt(coordinator, name, deviceID),
        FoxESSSCurrent(coordinator, name, deviceID),
        FoxESSSFreq(coordinator, name, deviceID),
        FoxESSSPower(coordinator, name, deviceID),
        FoxESSSVolt(coordinator, name, deviceID),
        FoxESSTCurrent(coordinator, name, deviceID),
        FoxESSTFreq(coordinator, name, deviceID),
        FoxESSTPower(coordinator, name, deviceID),
        FoxESSTVolt(coordinator, name, deviceID),
        FoxESSReactivePower(coordinator, name, deviceID),
        FoxESSBatTemp(coordinator, name, deviceID),
        FoxESSAmbientTemp(coordinator, name, deviceID),
        FoxESSBoostTemp(coordinator, name, deviceID),
        FoxESSInvTemp(coordinator, name, deviceID),
        FoxESSBatSoC(coordinator, name, deviceID),
        FoxESSBatMinSoC(coordinator, name, deviceID),
        FoxESSBatMinSoConGrid(coordinator, name, deviceID),
        FoxESSSolarPower(coordinator, name, deviceID),
        FoxESSEnergySolar(coordinator, name, deviceID),
        FoxESSInverter(coordinator, name, deviceID),
        FoxESSGenerationPower(coordinator, name, deviceID),
        FoxESSGridConsumptionPower(coordinator, name, deviceID),
        FoxESSFeedInPower(coordinator, name, deviceID),
        FoxESSBatDischargePower(coordinator, name, deviceID),
        FoxESSBatChargePower(coordinator, name, deviceID),
        FoxESSLoadPower(coordinator, name, deviceID),
        FoxESSEnergyGenerated(coordinator, name, deviceID),
        FoxESSEnergyGridConsumption(coordinator, name, deviceID),
        FoxESSEnergyFeedin(coordinator, name, deviceID),
        FoxESSEnergyBatCharge(coordinator, name, deviceID),
        FoxESSEnergyBatDischarge(coordinator, name, deviceID),
        FoxESSEnergyLoad(coordinator, name, deviceID),
        FoxESSResidualEnergy(coordinator, name, deviceID)
    ])
![Screenshot 2024-03-05 165646](https://github.com/macxq/foxess-ha/assets/86977015/f8faaa48-fad0-401a-9911-d89a3473a67a)

**HA version:**

**foxess-ha version:**

**Comment by FozzieUK** [comment]
Are both inverters in the same account ?, if they are when you are in the api_key screen you should see ~ 2,880 api calls remaining, in which case you would use the same api_key for both.

Just to double check you have updated your integration with the latest (v0.36) via HACS

In System, Logs can you click on ‘Load Full Logs’ at the bottom and copy any reference you see to ‘Foxess’ below please.

**Comment by chesterflaps** [comment]
> Are both inverters in the same account ?, if they are when you are in the api_key screen you should see ~ 2,880 api calls remaining, in which case you would use the same api_key for both.
> 
> Just to double check you have updated your integration with the latest (v0.36) via HACS
> 
> In System, Logs can you click on ‘Load Full Logs’ at the bottom and copy any reference you see to ‘Foxess’ below please.

Yes, it says 2,880so that answers that question, thank you.

I have updated to the latest integration.

Logger: homeassistant.config
Source: config.py:1293
First occurred: 16:33:00 (2 occurrences)
Last logged: 16:33:00

Invalid config for 'sensor' from integration 'foxess' at configuration.yaml, line 32: required key 'apiKey' not provided, please check the docs at https://github.com/macxq/foxess-ha Invalid config for 'sensor' from integration 'foxess' at configuration.yaml, line 38: 'apikey' is an invalid option for 'foxess.sensor', check: apikey, please check the docs at https://github.com/macxq/foxess-ha
Invalid config for 'sensor' from integration 'foxess' at configuration.yaml, line 39: required key 'apiKey' not provided, please check the docs at https://github.com/macxq/foxess-ha Invalid config for 'sensor' from integration 'foxess' at configuration.yaml, line 45: 'apikey' is an invalid option for 'foxess.sensor', check: apikey, please check the docs at https://github.com/macxq/foxess-ha

**Comment by chesterflaps** [comment]
I worked it out from the logs I just posted. I didn't realise I could see those logs.

Turns out I put apikey instead of apiKey

**Comment by chesterflaps** [comment]
> Yep just noticed that too, I hope everything settles down for you 👍

I wish I could say it was all working but sadly it is not. The entities no longer have the red icons next to them but there is no data showing.
![Screenshot 2024-03-06 182316](https://github.com/macxq/foxess-ha/assets/86977015/9262c55c-962e-4e23-b8fc-eca3c5105718)

**Comment by FozzieUK** [comment]
I think it might be worth restarting HA, there have been some issues over the past few days with the openapi that now seem to have settled.

Once it has been restarted can you go back to your logs, click on the full logs and post anything you see that relates to foxess (assuming it doesn’t populate the sensors).

**Comment by chesterflaps** [comment]
Still no info. These are in my logs


Logger: custom_components.foxess.sensor
Source: custom_components/foxess/sensor.py:190
integration: foxess ([documentation](https://github.com/macxq/foxess-ha), [issues](https://github.com/macxq/foxess-ha/issues))
First occurred: 7 March 2024 at 16:43:09 (1930 occurrences)
Last logged: 09:01:34

FoxESS1 has Cloud timeout or the Inverter is off-line, connection will be retried in 1 minute.
FoxESS2 has Cloud timeout or the Inverter is off-line, connection will be retried in 1 minute.




Logger: homeassistant.components.sensor
Source: runner.py:188
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 7 March 2024 at 16:43:01 (2 occurrences)
Last logged: 7 March 2024 at 16:43:01

Setup of sensor platform foxess is taking over 10 seconds.

**Comment by FozzieUK** [comment]
Can you first double check that api_key is correct first, it's easy to lose a character when copying.

Also make sure when you generate it that you copy it to a note somewhere immediately as it only shows you it the once, thereafter it will contain asterisks as a security feature so it cannot be duplicated.

It should be in this format in blocks of 8-4-4-4-12

The numbers are hexadecimal so only numeric characters and a,b,c,d,e,f can be in the string with '-' in between

the hex letters are always lower case

so for example this an old one of mine, but the format will be similar:

2c557f7f-1ae8-46af-bb78-a124adbbd22b

If you are sure it is definitely correct, you will need to add some logging to your configuration.yaml file so we can see what error messages are being returned by the openapi.

Can you add these lines near the beginning of your configuaration.yaml file and then restart.

```
logger:
  default: warn
  logs:
    custom_components.foxess: debug

```

Once it has restarted, go to Settings, Logs and click on 'LOAD FULL LOGS' - there will be a lot of entries that relate to the integration, what I am looking for is the one that says -

2024-03-08 11:46:11.647 DEBUG (MainThread) [custom_components.foxess.sensor] OADevice Detail fetch https://www.foxesscloud.com/op/v0/device/detail?xxxxxxxxxxx

It will be followed immediately by a message that contains either a success message or an error - can you post that here please.

**Comment by chesterflaps** [comment]
I went into API on Fox dashboard and the API I generated the other day had gone and this is the screen I get now. 
![Screenshot 2024-03-08 214617](https://github.com/macxq/foxess-ha/assets/86977015/b2a82405-859d-4596-8d49-9bbaf7450c21)

Not done the other things as I can't get past the first step now.

I already put that bit of code in at the end, as per the instructions. Does it make a difference if it is at the end instead of the start? The documentation says put it at the end.

**Comment by FozzieUK** [comment]
Ok, it does look like there is something wrong getting your API key - as there have been quite a few problems this week with the cloud, can you check a couple of times a day - and assuming it works re-generate the key, copy it to a note so you can re-use it later and then replace the api_key in your configuration.yaml with that new code.

If it doesn’t let you get an api_key after a few days - you are going to need to raise a support request on FoxESS and have them work out why.

**Comment by chesterflaps** [comment]
> Ok, it does look like there is something wrong getting your API key - as there have been quite a few problems this week with the cloud, can you check a couple of times a day - and assuming it works re-generate the key, copy it to a note so you can re-use it later and then replace the api_key in your configuration.yaml with that new code.
> 
> If it doesn’t let you get an api_key after a few days - you are going to need to raise a support request on FoxESS and have them work out why.

Yeah still doing the same thing today. I will keep an eye on it. Thanks

**Comment by chesterflaps** [comment]
I've raised a ticket

**Comment by sma0071** [comment]
Hi, 
I am experiancing the same problem. Just wondering if this fault has been fixed or any update?

**Comment by FozzieUK** [comment]
@sma0071 The integration is working fine, this thread was just a configuration problem.

Can you say when it stopped working for you, and what version of the integration you have installed ?.

There was a breaking change about 7 weeks ago when Fox changed their api - if your version is any earlier than v0.33 it won’t work anymore and you’ll need to install the latest version.

Have a read through the [readme file](https://github.com/macxq/foxess-ha?tab=readme-ov-file#auxiliary-notes) as in the new version you have to add a deviceSN: and apiKey: to your configuration - the readme explains that. 

Obviously if you have updated your version and are having problems we need to explore why, so post back if that’s the case

**Comment by sma0071** [comment]
@FozzieUK 
It's a new installation, I have followed the readme file and I think I am confgured corectly. I had a problem with the deviceID as its not shown the same on my browser. 
![image](https://github.com/macxq/foxess-ha/assets/136631792/5dbe3751-2088-43f9-b557-4957ffff01f3)

My HA logs seem to reciving no data but no error.  any ideas?

**Comment by sma0071** [comment]
@FozzieUK , I think I have just fixed it, I found my deviceID on a different screen and added the username and password options. Not sure if it was the deviceID or the username and password that fixed it..... Thank you for a quick response.
![image](https://github.com/macxq/foxess-ha/assets/136631792/bdbb2f94-e025-473b-be23-041f43d7a7d0)

**Comment by FozzieUK** [comment]
@sma0071 Ok great, the username and password are mostly legacy now and not important but your deviceID is still used.
Any problems, please post back 👍
