### ISSUE TITLE
Second object gets first object data

### ISSUE THREAD

**Issue by webmake** [macxq/foxess-ha#232]
**Describe the bug**
I'm not sure is it this plugin bug, or homeassistant, but one time I've noticed a weird graph, when there was no electricity in second object, and second object received first object data with time delay. And electricity came back at around 10o'clock. I saw that api data was correct, so maybe there is a mistake with entities.

**Screenshots**
![image](https://github.com/macxq/foxess-ha/assets/5016464/304cce70-842a-4fcc-a60e-db2d63a206cb)

**HA version:**
Home Assistant 2023.6.2

**foxess-ha version:**
v0.36

**Comment by FozzieUK** [comment]
It's a weird one, almost as if no data results in it using the other inverters data ?.

Can I double check which entity you are looking at there - is that generation power on 2 different inverters ?

Can you use the  Foxess cloud website and copy and paste the graphs of what each of the generation powers was doing during that same time period (that entity is called 'Output Power' in the fox cloud dropdown list)

**Comment by webmake** [comment]
I have some data logged at that time, not sure if this will help
[log_duplicated.txt](https://github.com/macxq/foxess-ha/files/14696367/log_duplicated.txt)

**Comment by webmake** [comment]
Adding minimized and mapped logs
[log_duplicated_simplified.txt](https://github.com/macxq/foxess-ha/files/14696748/log_duplicated_simplified.txt)

**Comment by FozzieUK** [comment]
It’s a difficult one to test for - I would have expected the inverter status to have gone off-line and it would stop polling for variables but that doesn’t seem to be the case - i’ll setup a multi-inverter system and take a look at it.
Can I double check that in your configuration.yaml ‘platform’ that you have a unique deviceID for each of the inverters.

**Comment by FozzieUK** [comment]
https://github.com/macxq/foxess-ha/releases/tag/v0.38 corrects this, when an inverter goes off-line it will correctly show the raw data entities as unavailable and the inverter status will show off-line.
