### ISSUE TITLE
All entities gone to unknow after update to v0.38

### ISSUE THREAD

**Issue by dario-io** [macxq/foxess-ha#235]
**Describe the bug**

**To Reproduce**
1. Go to Settings - Device and Services - Entities tab
2. Click on serchbar - type foxess
3. Click on one of the entities 

**Expected behavior**

**Screenshots**
<img width="594" alt="Screenshot 2024-03-27 alle 13 11 09" src="https://github.com/macxq/foxess-ha/assets/76044232/24ebb3dc-b011-4514-8b67-4ddca4362f47">
<img width="594" alt="Screenshot 2024-03-27 alle 13 10 57" src="https://github.com/macxq/foxess-ha/assets/76044232/a6be6bf9-2857-40a5-a21b-63dc4a5607ba">

**Debug logs:**
<img width="651" alt="Screenshot 2024-03-27 alle 13 13 31" src="https://github.com/macxq/foxess-ha/assets/76044232/7b080b61-b2a1-4495-8ee3-0369b68db42f">

**HA version:**
Core: 2024.3.3
Supervisor: 2024.03.0
Operating System: 12.1
Frontend: 20240307.0

**foxess-ha version:**
0.38

**Comment by ecbos1967** [comment]
Same for me, the integration starts working again after a reboot of HA. Next day it stops again until I reboot

**Comment by FozzieUK** [comment]
Can you check what the ‘inverter’ sensor shows - is it showing ‘off-line’

If you revert back to your previously used version does it work ok ?

**Comment by ecbos1967** [comment]
It is on a rpi4-64, the inverter is the Foxess ESS F4600. During the night the inverter goes into a sleep mode and it seems that HA does not re-connect when the inverter goes back online. The log shows: "FoxESS has Cloud timeout or the Inverter is off-line, connection will be retried in 1 minute". When I restart HA it comes online again. Have not yet tried to go back to the previous version, will try that today

**Comment by FozzieUK** [comment]
Thanks for that, very helpful.

Just looking at it now, I think whilst adding the improved off-line handling, I have added a bug where if an inverter goes into standby, the integration will never see it come out again - which is what you are seeing, apologies.

I will do some testing for this later today, and hope to get a fix out shortly (v0.37 will run ok)  - I will update this post to confirm.

**Comment by kamyk** [comment]
Hi,
Same for me. I have just revert to older version. Waiting for fix.
Best

**Comment by FozzieUK** [comment]
Hi all, can you please download and try the latest release v0.39, this corrects the off-line handling 'unavailable' entity problems of v0.38 and will correctly follow the inverter status as it switches on and off-line.

Please note whilst off-line, the integration checks site status every 5 minutes (not every 1 minute) so it does not use too many API calls.

https://github.com/macxq/foxess-ha/releases/tag/v0.39

**Comment by ecbos1967** [comment]
I can confirm it is working as expected on v0.39, thanks for your efforts to maintain this integration

**Comment by FozzieUK** [comment]
That's great, thanks very much.

I'll leave the issue open for a few days, and anybody with v0.38 can see there is a fix. 👍
