### ISSUE TITLE
Data stalls, no recent config changes only HA update to latest version

### ISSUE THREAD

**Issue by jdiviney** [macxq/foxess-ha#237]
2 episodes of data stalling with no updates.
No config changes, just updated to latest HA version.
Data in Foxess app is still live.
Resolves on HA restart for 90 mins or so and then no further new data. 
![Screenshot_20240414_112102_Home Assistant](https://github.com/macxq/foxess-ha/assets/47598678/67e7fbe2-41cf-4331-ad6b-fb20b4b59d6c)

**Comment by FozzieUK** [comment]
What inverter do you have, is it hybrid or solar only inverter ?

Can you put up a trace from another sensor such as 'Bat Discharge Power' when this happens.

I'm running the latest HA version and no problems with data - what version of HA Core, Supervisor, OS are you running and which version of the integration are you running ?

**Comment by jdiviney** [comment]
Thanks so much for the response. 
Hybrid
![Screenshot_20240414_123215_Home Assistant](https://github.com/macxq/foxess-ha/assets/47598678/a19ec89e-d58c-481d-a1c7-1dba1436bb2f)
Core: 2024.4.3
Supervisor: 2024.04.0
Addon: 0.39

**Comment by FozzieUK** [comment]
Ok, thanks - i’m running the same versions ok, are there any errors around the time it happens?
You can see more information in Settings, System, Logs then click the ‘LOAD FULL LOGS’ button, we’re looking for any errors, timeouts, failures etc.. around the time it happens reported by the foxess integration.

As you are running v0.39 you will have another sensor called response_time - that is monitoring the response time from the foxess openapi - could you also post that trace for the same period.

**Comment by jdiviney** [comment]
Hasn't recurred since but will post the above if it does.
Thanks!
