### ISSUE TITLE
Not all MPPT telemetry is being pulled.

### ISSUE THREAD

**Issue by Sarelseekat** [macxq/foxess-ha#240]
We have an H3 Pro with 6 MPPTs but only 4 pull-throughs to home assistant. Could this be because there is no API call for the extra two strings?

**Comment by Sarelseekat** [comment]
I'm available all weekend so I can share the API-key and SN with you. Will have to generate a new key though.

**Comment by FozzieUK** [comment]
see https://github.com/macxq/foxess-ha/issues/239#issuecomment-2067947433 - PV5 and 6 available in the test branch

**Comment by Sarelseekat** [comment]
Working 100% with the new Update you provided.
