### ISSUE TITLE
Add Inverter Status - on-grid & off-grid

### ISSUE THREAD

**Issue by timsdrew** [macxq/foxess-ha#246]
Hi,

Have an H3-Pro (extremely happy I'm now getting battery SOC%) and would like to be able to detect if the grid is down or not. Looking for the API, it does appear to be available, but not sure if available for the H3-Pro:

>   runningState:
      name:
        zh_CN: 运行状态
        en: Running State
        pl: Running State
        fr: Running State
        pt: Running State
        de: Running State
      unit:
      Grid-tied inverter: true
      Energy-storage inverter: true
      enum:
        160: self-test
        161: waiting
        162: checking
        163: on-grid
        164: off-grid
        165: fault
        166: permanent-fault
        167: standby
        168: upgrading
        169: fct
        170: illegal

**Comment by FozzieUK** [comment]
Hi, 

The running state 'enum' is available for the H3 Pro via the openAPI but not the grid tied or energy storage flags (these come from a separate device detail api call). I can add the running state entity for you on the next update.

I've also noticed that battery temperature doesn't get populated for the H3 Pro so i'll fix that at the same time.

FYI - the battery charge and discharge power 'totals' reported by the Fox cloud (and shown on their website) appear to be calculated for just 1 of the batteries, there is a post that discusses it [here](https://github.com/macxq/foxess-ha/issues/239#issuecomment-2075039698) if it affects you would you mind raising a ticket as well (every little helps)

**Comment by timsdrew** [comment]
Thanks! Only interested in the running state enum not the grid tied or energy storage flags so all good from me.
I saw the post this morning and don't think I have the issue as I only have 1 battery connected (for now) so it appears to be working, but will investigate more and register a ticket if necessary.

**Comment by FozzieUK** [comment]
See https://github.com/macxq/foxess-ha/releases/tag/v0.40b1

Note this is a beta release at this stage, you will need to have 'show beta versions' enabled in HACS when you redownload
