### ISSUE TITLE
generated total power entity unvailable

### ISSUE THREAD

**Issue by mohamedmallek1982** [macxq/foxess-ha#248]
**Describe the bug**
the power generated became unvailable

in sensor card and energy dashboard generated power not shown
was working good

**Expected behavior**
see total kw produced by the inverter 

**Debug logs:**

**HA version:**
12.3
core
2024.5.2

**foxess-ha version:**
0.40

**Comment by FozzieUK** [comment]
I’m still seeing the sensor.foxess_generation_power working ok but there have been problems with the OpenAPI recently which is causing timeouts.
![IMG_1589](https://github.com/macxq/foxess-ha/assets/113460294/f81642ea-d0e0-47ae-8e09-0fb2c9cdcc9b)

Are you having problems with any other sensor, can you display a graph of what that sensor is reporting please

**Comment by mohamedmallek1982** [comment]
![Capture d’écran (1)](https://github.com/macxq/foxess-ha/assets/164400252/60e3ce9e-a8e4-4843-bccf-0b6d0f1a46b4)

i don't see my previous entites 
Foxess Grid generated power
it's after update to core 2024.5.2 and HA 12.3

**Comment by mohamedmallek1982** [comment]
![Capture d’écran (2)](https://github.com/macxq/foxess-ha/assets/164400252/6f233f3d-592c-409e-adb4-30c3906dda3d)
i'm a new in HA 
and still in VM not all time on now.

**Comment by mohamedmallek1982** [comment]
![Capture d’écran (3)](https://github.com/macxq/foxess-ha/assets/164400252/afe547d3-06bc-4778-8f23-86db774bb216)

you see sensor not found 
maybe it's related to foxess 

![Capture d’écran (4)](https://github.com/macxq/foxess-ha/assets/164400252/0a9e733f-c735-4c8f-aea9-28bf31a65f71)

and i notices that status runnig 170:illegal

**Comment by mohamedmallek1982** [comment]
I check application in Android 
Foxcloud 
The generated power daily is no.more accessible 
![Screenshot_20240509_210234_FoxCloud](https://github.com/macxq/foxess-ha/assets/164400252/03d15a3f-291b-461d-94e2-04a075fb74db)
And even in website the power generated is only shown in statistics.
So i installedanother app 
Energy Stats and there it show generated power of the day in stats
![Screenshot_20240509_210251_Energy Stats](https://github.com/macxq/foxess-ha/assets/164400252/3778c996-9d9f-4d5a-a75a-013988ad7f05)

**Comment by mohamedmallek1982** [comment]
![Screenshot_20240509_211339_Samsung Internet](https://github.com/macxq/foxess-ha/assets/164400252/8dc733be-9d2c-4735-b90c-4e786f1cd3fe)

**Comment by FozzieUK** [comment]
Yeah, i’m pretty sure we are looking at issues with the Foxess servers - the OpenAPI has been struggling but even their private servers have been off-line today.
