### ISSUE TITLE
OA Device Detail Bad Response (sensor.py:392;193) illegal timestamp

### ISSUE THREAD

**Issue by sMfoe** [macxq/foxess-ha#262]
Hello everyone and thank you for the integration.

I'm  new in using Home Assistant I set it up with known config:

./configuration.yaml

```
sensor:
  - platform: foxess
    deviceID: acbeac2d-****-****-****-************
    deviceSN: 605************
    apiKey: 7ba*********************
```
 
Seems it's counting requests on FoxESS -Page:
> Anzahl der Anrufe pro Tag:1440
> Verbleibende Anrufe für heute:979

 

But I got this issues:

1.  
> Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> Logger: custom_components.foxess.sensor
> Quelle: custom_components/foxess/sensor.py:392
> Integration: foxess (Dokumentation, Probleme)
> Erstmals aufgetreten: 12:54:18 (65 Vorkommnisse)
> Zuletzt protokolliert: 14:39:52
> OA Device Detail Bad Response: {'errno': 40256, 'msg': 'Parameter could not be parsed correctly illegal timestamp'}
> OA Device Detail Bad Response: {'errno': 41930, 'msg': 'Device does not exist or has been used by other', 'result': None}

2.
> Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> Logger: custom_components.foxess.sensor
> Quelle: custom_components/foxess/sensor.py:193
> Integration: foxess (Dokumentation, Probleme)
> Erstmals aufgetreten: 12:54:23 (29 Vorkommnisse)
> Zuletzt protokolliert: 13:42:37
> FoxESS has Cloud timeout fetching Device Detail, will retry in 1 minute.

Since install I was not able to get **any** data in **every** entity of FoxESS:
 
![FoxESS_BatSoC](https://github.com/user-attachments/assets/7a138e55-a546-44f3-8eea-3c03e49cedb9)

Maybe someone has an idea what the problem is.

Thank you very much.

Greetings

**HA version:**
Core 2024.7.2
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

**foxess-ha version:**
v0.42

**Hardware**
Synology DS923 VM 2CPU 4GB RAM

**Comment by FozzieUK** [comment]
The OpenAPI is suffering with performance problems at the moment, FoxESS are aware but there is no resolution as of yet.

The API usually responds well in the morning and later at night but it has timeouts usually from noon onwards - and this is the error that you will see from the timeout  `OA Device Detail Bad Response: {'errno': 40256, 'msg': 'Parameter could not be parsed correctly illegal timestamp'}` - it’s not normal but there is nothing we can do until FoxESS fix the timeouts.

But this error `OA Device Detail Bad Response: {'errno': 41930, 'msg': 'Device does not exist or has been used by other', 'result': None}
` is saying that your apiKey is correct but the deviceSN cannot be found in that account. 
Double check that your deviceSN is correct and that you havn’t got an ‘O’ in place of a ‘0’ (zero) or vice versa, it’s easiest to copy and paste the SN from the website that way you know it’s accurate.

**Comment by sMfoe** [comment]
Thank you for your fast answer
The deviceID needs to be with/without - hyphens (and/or apiKey as well ?)
and needs any statement in the configuration.yaml with/ quotation marks?

**Comment by FozzieUK** [comment]
The deviceID should be with hyphens, but it isn’t critical as with the latest integration the only thing it must be is unique to your installation.

The deviceSN should be your inverter serial number (not the datalogger serial number) and must be exactly as you find it on the website.

The apiKey **must** contain hypens and is exactly as you find it when the website generates it and it’s in the format 8-4-4-4-12 characters.

**Comment by sMfoe** [comment]
Hi @FozzieUK ,
I reinstalled the integration once more (after a roleback)
now it's running - seems there was a typo between 5 and S
thanks for all your hints - we can close the issue as solved
![FoxESS_running2024-07-14_195940](https://github.com/user-attachments/assets/5a9ffc8b-ed2c-4354-87f2-c273e3d094b6)

**Comment by sMfoe** [comment]
I can only recommend to create a backup beforehand in advance and highlight that great community here to get started with HA
thank you

**Comment by FozzieUK** [comment]
Thanks, your welcome 🙏
