### ISSUE TITLE
FoxESS Running State: is expired

### ISSUE THREAD

**Issue by Dirk-Dirk-Dirk** [macxq/foxess-ha#264]
As of this afternoon, the FoxESS data is no longer available to me in HA.
The logbook states:
2024-08-02 14:48 - FoxESS Running State: is expired
2024-08-02 14:48 - FoxESS Inverter:  is expired
2024-08-02 15:20 - FoxESS Inverter:  changed to offline

I renewed the API Key because I suspected it had expired, but nothing changed; no FoxESS data found.
Does anyone have an idea what's going wrong here? 
Everything worked perfectly since the last update v0.36 in March 2024. 
The app and the website (FoxESS cloud) also work normally.

**Comment by FozzieUK** [comment]
The Fox OpenAPI is down at the moment, and i’m hearing the V2 app is also affected - it’s been dodgy most of today - looks like they must be working on their servers.

**Comment by jt1Kirk** [comment]
I have the same Problem. 
![Screenshot 2024-08-02 164326](https://github.com/user-attachments/assets/d5f03c69-f154-4a23-ab43-8aea18d7a041)

**Comment by Dirk-Dirk-Dirk** [comment]
Okay, we'll wait and hope for the best

**Comment by ssherlock** [comment]
This explains why my own app, that uses their API, isn't returning data

Simon

**Comment by FozzieUK** [comment]
It appears to be back up again 👍

**Comment by Dirk-Dirk-Dirk** [comment]
Indeed, Foxess Cloud Data is available again!

**Comment by pattos123** [comment]
Seems to have been worth it! Much better API response times yesterday, so guess they've upgraded their servers. Thanks to anyone who pressed FoxESS to improved their service.

**Comment by fpacardoso** [comment]
I have  170: illegal  on my running state, but the system is working fine.
Any ideias why this state?

**Comment by FozzieUK** [comment]
> I have 170: illegal on my running state, but the system is working fine. Any ideias why this state?

Sorry no idea, this state comes reported directly from the Fox OpenAPI

```
  - runningState:
      name:
        zh_CN: 运行状态
        en: Running State
        pl: Running State
        fr: Running State
        pt: Running State
        de: Running State
      unit:
      Grid-tied inverter: true
      Energy-storage inverter: true
      enum:
        160: self-test
        161: waiting
        162: checking
        163: on-grid
        164: off-grid
        165: fault
        166: permanent-fault
        167: standby
        168: upgrading
        169: fct
        170: illegal
```
what inverter do you have ?

**Comment by fpacardoso** [comment]
My inverter is S3000-G2. There is any explanation for all status?

**Comment by FozzieUK** [comment]
No, that's all you get in the documents - what state do you see if you look in the Fox V2 app (just above the solar panels on the house image)

**Comment by fpacardoso** [comment]
> No, that's all you get in the documents - what state do you see if you look in the Fox V2 app (just above the solar panels on the house image)

I have on Top right "Normal" "ON GRID".

**Comment by FozzieUK** [comment]
Hmm, sounds ok - It could simply be that Fox have not passed the status of your inverter model correctly into the OpenAPI

**Comment by fpacardoso** [comment]
Just to update.
FoxESS suporte
`we noticed the API port has some bugs.
We are working on fixing this issue and will release it next week.`

**Comment by fpacardoso** [comment]
My Running state its ok now. Today I can see all the states after inverter power on.
