### ISSUE TITLE
Foxess 75R - Cant view all photovoltaic inputs

### ISSUE THREAD

**Issue by jrrrenofio** [macxq/foxess-ha#265]
I have a Foxess 75R. I was able to install the integration in HomeAssistant and I was able to access some data. However, this inverter has 9 MPPTs. Each of the 9 MPPTs has 2 inputs and so in Foxcloud I have 18 photovoltaic inputs. Through the integration I can only observe 6 photovoltaic inputs. Is it possible for the integration to provide me with the information for the 18 inputs?

**Comment by FozzieUK** [comment]
Hi, that's a lot of PV inputs !

I've checked the OpenAPI and it does show variables for up to 18 strings, so it should in theory be possible to add this to the integration.

I don't have access to anything that has that many string inputs, so I have 2 options either I add them and hope they are coded correctly for you to test - or if you could share your api_key and inverter serial number with me, I can test them and once working release the tested version. 
If you are ok sharing the details (you can change the api_key later), please email them to me at b5djf@yahoo.com and as soon as I get some spare time i'll add the extra strings for you.

**Comment by jrrrenofio** [comment]
Hi, thank you very much for your feedback!

I believe that at first it would be better to continue with the first option. 

I am available to do any testing you need.

Thanks again

**Comment by FozzieUK** [comment]
ok, i'll try and get some time over the weekend to look at it 👍

**Comment by FozzieUK** [comment]
@jrrrenofio 
Hi, i’ve added the extra PV strings in a pre-release version( v0.42-beta-1 ), this should support the full 18 strings (and associated entities volts, current, power).

I’d be grateful if you could test it with your R series and confirm the extra string entities are working as expected.

You’ll need to update to this version (if on the old HACS, click the redownload link and check the show beta versions), if you are on the latest HACS2 just select and download v0.42-beta-1.

Before you restart home assistant, you need to add an extra config item in your configuration.yaml file `extendPV: true` - note the case it is precise - without this the extra strings will not be enabled (it avoids adding 36 unnecessary entities for most users)

```
sensor:
  - platform: foxess
    deviceID: enter_your_inverter_id
    deviceSN: enter_your_inverter_serial_number
    apiKey: enter_your_personal_api_key
    extendPV: true
```

When your home assistant starts, the integration will put a confirmation in the log that it has detected the extra string config as follows.
`September 14, 2024 at 5:48:03 PM – (WARNING) Sensor
 Extended PV 1-18 strings enabled
 September 14, 2024 at 5:47:53 PM – (WARNING) foxess (custom integration)`

**Comment by jrrrenofio** [comment]
Hi @FozzieUK ,

Now I can see the 18 PV inputs. I will monitor and analyze the information I am receiving. Thank you very much!

If you allow me, I have a question: can you see the total energy generated by the inverter through the API? And the timestamp of the last data report from the inverter?

In the FoxESS - Running State sensor, I am receiving the information 170: illegal, but from what I could see in other issues, this is the information presented in the API.

Thanks again for your help!

**Comment by FozzieUK** [comment]
Not all inverters show all the statistics but I would hope that you would see the total generated in the Energy Generated entity (as this is a cumulative total it is only collected every 60 minutes).

There is no timestamp included in the received data but if your inverter is ‘on-line’ the last data sample will be no longer than 5 minutes old.

It sounds like you might have to raise a support ticket with Foxess as i’m pretty sure you are the first R series user and in the past the running state happens when they haven’t yet added it to the OpenAPI.

**Comment by jrrrenofio** [comment]
I can only observe the following energy entities:
1) sensor.foxess_energy_generated;
2) sensor.foxess_energy_generated_month;

Based on my observation, the entity sensor.foxess_energy_generated tracks energy generated daily. 

I cannot observe an entity that accumulates generation data throughout all the days the inverter is in operation.

I'm trying to calculate the energy generated per month, per week and per hour based on the sensor.foxess_energy_generated entity. I think that's why in my calculations the energy per hour is resulting in zero. 

I have some other entities that are showing an unknown state such as:
1) sensor.foxess_reactive_power
2) sensor.foxess_power_factor
3) sensor.foxess_energy_throughput (I have no idea what this entity represents.. :))

As you advised, I'll try to contact support to check the problem mentioned.

Also, as soon as I can, I'll analyze the data I'm receiving regarding the PV inputs.

Thank you very much for your attention!

**Comment by FozzieUK** [comment]
Of the 3 sensors you mention, the first 2 are for 3 phase systems and the last one is for battery storage systems - your system will never be able to populate them.

I believe that I can get access to your energy generated (cumulative) which will contain the count of energy through the inverter from inception - i’ll have a look at that for you.

As this is a new home assistant install the energy generated daily and monthly won’t have any history attached but over time they will produce far more meaningful statistics.

**Comment by jrrrenofio** [comment]
Hi Dave,

So, the Foxess 75R is a three-phase inverter.

It would be really helpful if you could give me access to the accumulated generation. I think it would solve the problems I'm having with my stats.

**Comment by FozzieUK** [comment]
> Hi Dave,
> 
> So, the Foxess 75R is a three-phase inverter.
> 
Sorry I should have been more specific with the first 2 sensors and say 3 phase ‘hybrid’ system.

> It would be really helpful if you could give me access to the accumulated generation. I think it would solve the problems I'm having with my stats.

Ok, leave it with me and i’ll check it out.

**Comment by jrrrenofio** [comment]
@FozzieUK, I have already updated to the new version and I was able to observe the accumulated generated energy sensor.

Thank you very much.

**Comment by FozzieUK** [comment]
Ok great, i’ll leave this open and assuming you have no issues in the next week or so, i’ll update the readme and do a formal release 👍

**Comment by jrrrenofio** [comment]
I consider this issue resolved. Thank you very much, Dave.

Thank you again for creating this integration and solving my issue. I'm here to help with anything you may need to improve this integration.

**Comment by FozzieUK** [comment]
No problem, thank you 👍 

I will convert this to a formal release v0.43 later this week.
