### ISSUE TITLE
Some sensors not working  - F5000

### ISSUE THREAD

**Issue by RyanStapleton80** [macxq/foxess-ha#27]
Thanks for the integration. I have a few issues with some of the sensors not gathering data. 
The sensors for feedin power, Grid consumption, Grid consumption power, load and solar all don't show any data. My system is a Foxess inverter model F5000. The datalogger is W2 version 3.03 .
I'm using version 0.11.2 of the integration in Home assistant (installed via Hacs).
The fox cloud app shows all of these sensor readings. 

Any help would be greatly appreciated.

**Comment by macxq** [comment]
Can you share your logs? 
Please make sure you enable debug level for foxess -> https://github.com/macxq/foxess-ha#-troubleshooting

**Comment by macxq** [comment]
@RyanStapleton80  closing the issue because I do not have scenario to replicate from you and any insight about his problem
