### ISSUE TITLE
Foxess data unavailable but working in apps (API verison change?)

### ISSUE THREAD

**Issue by jamesoff** [macxq/foxess-ha#278]
**Describe the bug**
Since 0215 this morning (GMT/UTC) HA has been unable to fetch data from Foxesscloud and all sensors are "unavailable".

The Foxess app, site and the 3rd party "Energy Stats" app are all working.

**To Reproduce**
The issue occured by itself while I was asleep. I have not changed my API key, and I've restarted HA in an attempt to fix it but it didn't help.

I see at https://www.foxesscloud.com/public/i18n/en/OpenApiDocument.html they updated the API today (27 November) which I guess may be the cause?

**Debug logs:**

The following two lines repeat continuously in the logs.
```
2024-11-27 07:47:00.148 ERROR (MainThread) [custom_components.foxess.sensor] OA Device Detail Bad Response: {'errno': 41200, 'msg': 'Query data failed', 'result': None}
2024-11-27 07:47:02.149 WARNING (MainThread) [custom_components.foxess.sensor] FoxESS has Cloud timeout fetching Device Detail, will retry in 1 minute.
```

**HA version:**
2024.11.3

**foxess-ha version:**
v0.43

**Comment by FozzieUK** [comment]
The OpenAPI appears to be having trouble and affecting all users at the moment - lots of reports coming in.

**Comment by jamesoff** [comment]
Thanks! I thought it may be (especially with the recent change) but having had a poke around couldn't immediately see any other similar reports. I'll sit tight :)

**Comment by udochrist** [comment]
Thanks for the Info. @FozzieUK should the integration recover automatically once foxess has sorted their issue or is a ha restart necessary?

**Comment by mbezik** [comment]
ive tried a HA restart and no joy, im wondering if a new API key should be generated to fix the issue or just wait it out?

**Comment by FozzieUK** [comment]
@mbezik No don't change your apikey it's the API that is returning a fault - just wait it out.

@udochrist As soon as the API returns a non error state the integration will restart on it's own - fingers crossed it won't be long 😞

**Comment by mbezik** [comment]
will do 👍🏻

**Comment by Dirk-Dirk-Dirk** [comment]
Apparently the status is still offline at 1:41 PM?
This is taking longer than expected...

**Comment by FozzieUK** [comment]
@Dirk-Dirk-Dirk it's been reported to them, you could always try raising a support ticket with them to say the OpenAPI is reporting 41200 errors, you never know the more people that complain the quicker they may fix it ;)

**Comment by Sarelseekat** [comment]
Hi there. Were can we report it to Fox?

**Comment by FozzieUK** [comment]
> Hi there. Were can we report it to Fox?

Probably the best way is to email your local Fox service centre, details here https://www.fox-ess.com/get-in-touch/

And I think this ticket system is still in operation https://support.fox-ess.com/portal/en/newticket?departmentId=121225000000549198&layoutId=121225000000564485

**Comment by Dirk-Dirk-Dirk** [comment]
FoxESS replied to the Ticket I submitted yesterday: 
    "There was something wrong with the server yesterday, but it has now been fixed. You can check if it has returned to normal now.
    If you have any further questions, please contact us."_
Everything now works as before.

**Comment by FozzieUK** [comment]
Yes also seeing the same, back up and no errors 👍

**Comment by sMfoe** [comment]
I‘ve got a „nice“ answer of the German support: ;-)
Die Anzahl der API-Aufrufe pro Tag ist durch unseren Server limitiert. Sie können die tägliche Freigrenze in Ihrem Konto einsehen. 
even I sent them the LOG with 41200
2024-11-27 23:05:41.801 ERROR (MainThread) [custom_components.foxess.sensor] OA Device Detail Bad Response: {'errno': 41200, 'msg': 'Query data failed', 'result': …
But nevertheless after one day I retrieve now valid data again
