### ISSUE TITLE
Token issue ?

### ISSUE THREAD

**Issue by Daibutt** [macxq/foxess-ha#3]
Hi, 
Just want to say this is fantastic!
I've been badgering FoxESS for last couple of months about an API or modbus acccess/register addresses & nothing so far from them.
If more of the invterter details are available (per Big Dave) that woud be great.
One question ...
When I github installed it went fine, got (daily) Yield & current production numbers correctly in HA immediately
I then logged back in to the Web UI, and none of the HA values have changed since. 
Have I "lost" the token for HA ? (Similar to when you acccess via mobile app vs Web UI?).
Do I need to restart HA to reinitiate the the token?

**Comment by macxq** [comment]
@Daibutt do you still observing this bug ?

**Comment by Daibutt** [comment]
@macxq Sorry , I should have updated. No, this is no longer an issue. With one of the recent releases everything is working fine.
