### ISSUE TITLE
[Review] - Changes to reduce API load on foxesscloud.com

### ISSUE THREAD

**Issue by warmfusion** [macxq/foxess-ha#41]
# FoxESS-HA Plugin Review

As seen in https://github.com/macxq/foxess-ha/issues/28, there is an increasing frequency of endpoint blocking and service instability on the FoxESSCloud.com service endpoint.

Discussions with their support team have suggested that plugins such as this are increasing the workload on the hosts and causing the instability.

As such, the following is a review of the `sensor.py` source with a particular emphasis on where changes could be made to reduce overheads on FoxESS servers with minimal/no compromise to the available data to users.

The principal areas of sensor data are obtained from the following core api endpoints;

- Auth :: Obtaining credentials and tokens necessary to obtain the data feeds
- Raw data :: The inverter/battery raw data itself
- Report summary :: Higher level reporting on earnings, yield etc
- Earnings :: An assessment of the generated income of a particular device
- AddressBook :: A list of devices, inverters attached to the account

Each of these are represented by their respective CONSTANT in the sensor.py for ease of discovery.

## _ENDPOINT_AUTH

The auth gets reloaded each time the scan interval fires, auth processes tend to be quite heavy (and sometimes expensive) so it'd be good to find a way to cache the auth token and refresh only if required.

> *Recommendation:*
>
> A possible method here would be to perform a lightweight authenticated request again a endpoint such as the`/v0/plant/status/all` when the authAndgetToken function is called, returning a cached token if successful, and attempting a full reauth on errors.

##  _ENDPOINT_RAW

This endpoint provides a set of the raw data values for the solar system.

The default implementation appears to pull the data for the whole day, and does so every `SCAN_INTERVAL` minutes which is excessive.

The `getRaw()` only uses the 'lastElement' from the data returned, which further highlights how wasteful the API call to FoxESS is being as much of the data is being discarded.

> *Recommendation:* 
>
>Adjust the query on `ENDPOINT_RAW` to use `timespan: hour` to significantly reduce the volume of data being pulled
> - Attempts to use timespan:minute were unsucessful, and just returned empty data entities
> - one possible edge case; if `getRaw` is called before Fox has updated data, the returned object will be empty. A simple workaround would be to just return the last discovered value.

## _ENDPOINT_REPORT

`reportType: month` is used, and a conditional filter is applied to check the 'current day' and obtain just a single value. The website appears to be using `reportType: day` which returns a much smaller set of data and similar to ENDPOINT_RAW much of the data is being discarded each time.

> *Recommendation:*
>
> Adjust `ENDPOINT_REPORT` to use `reportType: day` 

## _ENDPOINT_EARNINGS

This endpoint returns the cumulative (`cumulate` in the api) and Y/M/Today revenue generated by a particular device.

My own data is entierly inaccurate and frankly this endpoint is a waste of time.

## _ENDPOINT_ADDRESSBOOK

This endpoint obtains a list of inverters, batteries etc etc attached to the authenticated user. At the moment this gets updated every `SCAN_INTERVAL`.

How often are people adding devices to their account if you're not an installer who has access to a better API anyway...?

> *Recommendation:*
>
> The 'address book' data is only useful once and shouldn't be reloaded every few minutes 
> - could this just load this at HA startup and if the data needs a kicking restart HomeAssistant, or worst case refresh daily with a sepereate 24 hour period datacollector?
> - Perhaps do this for the report and earnings data too?

# Additional Recommendations

These are my own recommendations based on a review of the implementation of sensor.py with a specific objective to reduce the API burden on foxesscloud.com.

1. Have configuration flags to allow users to select which data reports are useful to them
    - I personally have no interest in the 'earnings' data as its wrong, and the monthly report data is equally pointless to me
1. Remove the useragent trickery and set a clear and explicit user agent indicating the data is coming from this plugin, and perhaps which specific user account
    - Of course this would likely mean the plugin fails and/or is easily blocked, however I personally feel that we should be looking to be 'the better person' in these situations.
    - Note that the inclusion of the user ID in the user agent protects other users in the event of an explicit block

# Fox API Notes

Some general observations found while investigating the behaviour of the foxess API services themselves. No particular recommendations or suggestions, just a record of interesting things.

- The getRaw endpoint is very sensitive; for example setting '"minute": 02' results in `errno:40261` while `"minute": 2` works - This suggests whatever is deserialising the input saw 02 as a string and didn't map nicely.
- Setting `timespan: hour` appears to mean the minute/second attributes are ignored as setting to 0 or 59 has no impact on the returned data.
- Setting `timespan: minute` doesn't appear to work at all. Attempts to set for a specific minute with known data returns no useful information, however does not fail outright; there may be a subtle semantic detail on this that I'm missing but it certainly feels like a 'not implemented' feature
- Trying `reportType: hour` on the /report endpoint results in `runtime error: index out of range [3] with length 3%` suggesting a bug in their implementation when attempting to deserialise the input parameters.
    - Interestingly, the wording of this response tells us the implementation is based on go 
    - Adding minute/second attributes to the request json does not change the response message

**Comment by macxq** [comment]
@warmfusion thank you for you engagement and contribution!  

**_ENDPOINT_AUTH**
Indeed -  this definitely should be fixed
I think that rather that calling `/v0/plant/status/all` we should try fetch the data as normal in case of `token_expired` error reauthenticate and repeat, this will truly help to limit the number of calls

**_ENDPOINT_RAW**
The suggested `timespan: hour` does not work for me, can you share an example curl ? 

**_ENDPOINT_REPORT**
👍 

**_ENDPOINT_ADDRESSBOOK**
This is returning not only address but also on/off status for inverter - in case of installation without battery it is use-full

**Configuration flags**
I was also thinking about this some time ago, with ability to configure it over the UI, it would be awesome

**Comment by macxq** [comment]
Auth token is cached and refreshed on demand i have also leveraged addressbook endpoint and do not fetched all data if inverter is offline

**Comment by Captain0Kangaroo** [comment]
So are we safe to turn HA back on now or will it result in a ban again ?

**Comment by macxq** [comment]
it is too early to say it is safe to turn in on again
