### ISSUE TITLE
[ FEATURE REQUEST] FoxESS MQTT suport

### ISSUE THREAD

**Issue by macxq** [macxq/foxess-ha#5]
This issue is to lavarag [Fox Cloud API Protocol.pdf](https://github.com/macxq/foxess-ha/files/7468664/Fox.Cloud.API.Protocol.pdf)

---
Host `foxesscloud.com` have `1883` port open:

![Screenshot 2021-11-03 at 16 26 13](https://user-images.githubusercontent.com/2965092/140090648-a4a3d3bf-1fd6-4a5d-a375-03a8e53e1e42.png)

But when I try to connect to it with settings: 

<img width="1028" alt="Screenshot 2021-11-03 at 17 10 22" src="https://user-images.githubusercontent.com/2965092/140098824-1292c908-72f5-4a77-a360-9dade36e395b.png">

`Bad username or password` is returned:

<img width="724" alt="Screenshot 2021-11-03 at 16 25 15" src="https://user-images.githubusercontent.com/2965092/140090512-13c76974-8f80-42cd-8991-d723f234cdee.png">

**Comment by macxq** [comment]
> The specific scope of authority is authorized and managed by the platform manufacturer.
I think this is crucial  ⬆️  and the MQTT is not available for everyone  😞

**Comment by benek984** [comment]
Hello, do you guys think there would be a way to pull mqtt from the inverter it self rather than from the cloud? 
@macxq are you related or have some access to Fox support? I tried to figure out one think but they never come back to me. Would you mind to talk privately?

**Comment by Daibutt** [comment]
Hi @benek984 , 
When I contacted Fox support they said MQTT was not for end users. Not sure why !
See this comment in a separate issue; https://github.com/macxq/foxess-ha/issues/2#issuecomment-954793424

**Comment by benek984** [comment]
yeach I had the same answer from them when I asked about APIs. Well I have now managed to use @macxq integration in HA  and all looks good. The only downside is that it relaying on cloud and data are pulled every 5min. With local MQTT I am guessing I could pull more often for more accurate data. 

Big thank you to @macxq I was fighting with Fox support for over 6month to get any info but no luck.

**Comment by Daibutt** [comment]
Ditto, I got no sense out of FoxESS. @macxq is a genius to work out how to get the API data.
You are not restricted to 5min resolution though @benek984.
You can change it if you have an agent account or ask your distributor/installer to change it. Default is 300 secs but I understand it can go as low as 30 secs. Mine is currently at 1 min.
![image](https://user-images.githubusercontent.com/69276073/147793877-1eae3637-1f27-4e9d-9b9f-ac749cec3aba.png)

If you go below 1min you may have to change scan interval in /config/custom_components/foxess-ha/sensor.py
![image](https://user-images.githubusercontent.com/69276073/147793749-e25fe611-8e03-41f8-b0cc-19a1bd233353.png)

**Comment by benek984** [comment]
@Daibutt THANK YOU SO MUCH for pointing me to the PUSH settings. Totally agree with you that  @macxq is a genius to work out how to get the API data !!!!!!

**Comment by williamjeccles** [comment]
Worth an update on this thread, FoxESS is now automatically setting the inverter configs back to 300 seconds even if you have it set for something faster locally so there is no point in changing the push level as it will always revert to 300 after a day or so.
On this subject, to make everyone aware that Foxess has been struggling with platform load so really you should be setting this scan_interval to as long as you can cope 5 -15 minutes is recommended.
