### ISSUE TITLE
Note from foxess

### ISSUE THREAD

**Issue by balloob** [macxq/foxess-ha#50]
I got the following e-mail from Foxess. I'm creating this issue and sending the link to them.

> Dear Friend of Home Asistant,
> 
> We are solar inverter&battery manufacture who supplies products to UK.
> Recently many of our end users are using Home Assistant together with Foxloud monitoring platform.
> Our products upload one package of data each 5 mins, while we found that Home Asistant is crewlering the data frequently which brings harm to our server.
> May we know:
> 
> 1. What data you are fetching?
> 2. What ways do you think is proper to fetch the data from our server?
> 
> We are looking for contact method of you as we have more and more common customers.
> Hope we can find a way to bring better experience to our common customers together.
> Looking forward to hear from you soon.
> Thank you.

@macxq I can also put you in contact with them via email if you prefer.

**Comment by macxq** [comment]
@balloob thx for reaching out to us! I'm already with contact with them :)
