### ISSUE TITLE
RS485 or Cloud over proxy.

### ISSUE THREAD

**Issue by straga** [macxq/foxess-ha#56]
May someone have RS485 protocol description.
OR does someone try to use a proxy for grab protocol between UNIT and Cloud?

Ideal variant like for Solax: direct connect do RS485, Use Cloud, Use Own Server with emulating Cloud.

**Comment by So5nA** [comment]
Supposedly MODBUS works on RS485. The condition is to have the manager sotware version 3.10 or higher.

**Comment by macxq** [comment]
use https://github.com/macxq/foxess-ha/discussion for discussions
