### ISSUE TITLE
Inverter states other than 1 no data... 

### ISSUE THREAD

**Issue by ianm993** [macxq/foxess-ha#58]
New user to GitHub so please excuse if not following protocol. I have looked through the issues and nothing jumped out. 

So after setting up HA and the dashboards, I came across this fine work done by @macxq, I noticed that I was not getting any data. The dashboards stated that the inverter was offline, and I was getting no data in HA, despite it being online in the fox cloud etc, and generating data. 

I checked the error log, and I noted there was a message "the inverter is offline, so not fetching data.". 
Further investigation led me to the sensor.py script, where I find "if int(allData["addressbook"]["result"]["status"]) == 1:" 
 which is checking for the status of 1, and reporting the above if it is anything but 1. 

My inverter has a status of 2, due to the fact that our installer has configured the battery, yet they have not got any in stock and doesn't look likely to be anytime soon. I have updated the check in my configuration to 2 and I get data now. 

I realise it is not a normal situation to have batteries configured and no batteries, but should the status of the inverger change in the future all data would not be reported.....

**Comment by williamjeccles** [comment]
@ianm993 as a temp workaround simply update your local script file to use 2 and then you can have it working until the batteries are installed and then switch it back to 1 once your batteries are online.

**Comment by ianm993** [comment]
@williamjeccles Thanks! I have done that, but as mentioned, should the status change then it would stop reporting. For me I know that the status is 2 because of the batteries, but if there is an actual error, then someone may not know why the data has stopped. 

Unfortunately I am not blessed with enough python knowledge (other than being an expert at hello world :D) to write it effectively but I think this maybe worth considering

**Comment by macxq** [comment]
@ianm993  thank you for reporting this!

Can you share state what exactly `device status` you have on the `inverted details` page ? 
<img width="1474" alt="Screenshot 2022-04-28 at 12 15 20" src="https://user-images.githubusercontent.com/2965092/165731676-902693d9-bfcd-4660-8a5d-b9281c585d18.png">

**Comment by ianm993** [comment]
@macxq - Inverter details states "Device Status: Alarm": 
![image](https://user-images.githubusercontent.com/104365850/165732579-5716806b-7b6c-424c-b360-adecd41107a6.png)

On the right hand side is an orange icon, with Today's alarm as per the image. Clicking on that shows this:
![image](https://user-images.githubusercontent.com/104365850/165732464-6b54c585-e7a2-4258-bf7c-7fc72112bd32.png)

**Comment by williamjeccles** [comment]
Maybe a config switch to ignore error states @macxq ?

**Comment by macxq** [comment]
@williamjeccles I want to handle this third state and extend `FoxESS - Inverter ` with it :) so proper  automation cold be made around this like sending notifications:)  
Data still will be fetched with this state

**Comment by jok001** [comment]
@ianm993 this is just what I needed to know. I've done the Home Assistant integration and got the inverter offline problem. Your little change worked brilliantly. Would really have struggled without this. 

Thanks.

**Comment by macxq** [comment]
beta version is addressing this https://github.com/macxq/foxess-ha/tree/v.0.2.0b  ⚠️ it's requires change in configuration!

**Comment by C00K50N** [comment]
I'm really glad I've found this thread!  @ianm993 I have the same situation as you; inverter and PV panels recently installed but no batteries yet until stock arrives.  Hence my inverter status is in "Alarm" and as such isn't providing any data to HA.  So thank you for pointing it out and describing the workaround until my batteries arrive.

**Comment by kylethompson30** [comment]
> New user to GitHub so please excuse if not following protocol. I have looked through the issues and nothing jumped out.
> 
> So after setting up HA and the dashboards, I came across this fine work done by @macxq, I noticed that I was not getting any data. The dashboards stated that the inverter was offline, and I was getting no data in HA, despite it being online in the fox cloud etc, and generating data.
> 
> I checked the error log, and I noted there was a message "the inverter is offline, so not fetching data.". Further investigation led me to the sensor.py script, where I find "if int(allData["addressbook"]["result"]["status"]) == 1:" which is checking for the status of 1, and reporting the above if it is anything but 1.
> 
> My inverter has a status of 2, due to the fact that our installer has configured the battery, yet they have not got any in stock and doesn't look likely to be anytime soon. I have updated the check in my configuration to 2 and I get data now.
> 
> I realise it is not a normal situation to have batteries configured and no batteries, but should the status of the inverger change in the future all data would not be reported.....

Hi, really new this HA - how do you find this script to amend the code? Trying to setup everything using @williamjeccles guide but am in the same boat with the error for no battery system.

Thanks

**Comment by macxq** [comment]
resolved with last release
