### ISSUE TITLE
Noob. HELP no data showing in overview page. 

### ISSUE THREAD

**Issue by Gpennell86** [macxq/foxess-ha#60]
Help total noob to home assistant. I can't get any data to show after following William's video on YouTube. The status of my inverter on the cloud page is normal. Any help or guidance is appreciated. 

![20220526_212504](https://user-images.githubusercontent.com/105997048/170579249-052dd0c0-9044-45b3-ad22-c96614a42796.jpg)
![20220526_211852](https://user-images.githubusercontent.com/105997048/170579261-3a8cf01b-7dbe-4eb1-a029-0763358b7a7d.jpg)

**Comment by Daibutt** [comment]
Under username password & deviceID I'm not sure you need the "foxesscloud" in front, unless it's changed in the last month...

**Comment by macxq** [comment]
@Gpennell86  is is as @Daibutt saying
your config should look like:
![Screenshot 2022-05-27 at 08 42 57](https://user-images.githubusercontent.com/2965092/170645598-725f52dd-8867-41e3-a6a4-61a287170651.png)

**Comment by Gpennell86** [comment]
Thanks, will give it a try.

**Comment by Gpennell86** [comment]
Still no joy, will start over with the install. My username and password are correct. 
![20220527_075318](https://user-images.githubusercontent.com/105997048/170648043-47849bfa-ceca-4a2b-8857-8e2e0caba7e5.jpg)

**Comment by macxq** [comment]
Can you share logs?

**Comment by Gpennell86** [comment]
After doing a delete & re-load of home assistant, HACS now has the custom repositories blanked out. Any help on this would be great. Thinking i shouldn't have bothered.  
![Screen Shot 2022-05-30 at 20 27 42](https://user-images.githubusercontent.com/105997048/171050813-f2732dcd-fedc-4560-8919-a0c5686aaf0e.png)

**Comment by Gpennell86** [comment]
Got it working now, thanks for your help. Bring on the graphs.
