### ISSUE TITLE
Integration not available despite downloading in HACS

### ISSUE THREAD

**Issue by ryaaanmorgan** [macxq/foxess-ha#65]
Not sure if I'm missing anything bleeding obvious here.

Having downloaded the FoxESS Cloud integration into HACS, restarted the system and configured the yaml file - I still cannot see the option to add the FoxESS Cloud when navigating to Settings > Devices & Services > Integrations > Add Integration.

What am I missing here?

I'm using a Raspberry Pi 3B+ with a SDD, for info.

Many thanks!

**Comment by macxq** [comment]
Do you see in logs such message?

`2022-07-04 12:05:18 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration foxess which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

**Comment by ryaaanmorgan** [comment]
There are additional entries in the log, see the image attached. I can assure you, the username and password is correct in the configuration file.

![Screenshot 2022-07-04 143542](https://user-images.githubusercontent.com/55667216/177165968-bfdd6ce1-ce32-4e51-9e7b-e0cd719cb8cd.png)

**Comment by macxq** [comment]
41807 error code is when  username and password  is wron - and maybe you have some bad formatting or whitespaces ?
![Screenshot 2022-07-20 at 09 28 13](https://user-images.githubusercontent.com/2965092/179922768-30d46d9e-00d1-4ba5-a7c3-577f1fa59ece.png)
