### ISSUE TITLE
New Error in logs, no data from Fox-Ess site

### ISSUE THREAD

**Issue by mhzawadi** [macxq/foxess-ha#67]
This error originated from a custom integration.

Logger: custom_components.foxess.sensor
Source: custom_components/foxess/sensor.py:143
Integration: foxess (documentation, issues)
First occurred: 02:33:14 (96 occurrences)
Last logged: 10:28:21

Unexpected error fetching FoxESS data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 143, in async_update_data
    if int(allData["addressbook"]["result"]["status"]) == 1:
TypeError: 'NoneType' object is not subscriptable

Version | core-2022.7.5
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.5
Operating System Family | Linux
Operating System Version | 5.15.32-v8
CPU Architecture | aarch64
Timezone | Europe/London
Configuration Directory | /config

Host Operating System | Home Assistant OS 8.2
-- | --
Update Channel | stable
Supervisor Version | supervisor-2022.07.0
Agent Version | 1.2.1
Docker Version | 20.10.14
Disk Total | 14.1 GB
Disk Used | 8.8 GB
Healthy | true
Supported | true
Board | rpi4-64
Supervisor API | ok
Version API | ok
Installed Add-ons | Check Home Assistant configuration (3.11.0), File editor (5.3.3), Mosquitto broker (6.1.2), Nextcloud Backup (0.17.6), Zigbee2MQTT (1.26.0-1), room-assistant (2.20.0), Terminal & SSH (9.6.0), SQLite Web (3.6.0), MariaDB (2.5.0), InfluxDB (4.5.0)

**Comment by macxq** [comment]
@mhzawadi can you enable debug level for logs 
```
logger:
  default: warning
  logs:
    custom_components.foxess: debug
```
and drop all logs from foxess integration from start of HA

**Comment by mhzawadi** [comment]
looks like a blip, have updated to `core-2022.7.6` and after restart its working
