### ISSUE TITLE
HA crash due to log file filling with MODBUS error

### ISSUE THREAD

**Issue by alexmercerscott** [macxq/foxess-ha#75]
Since around the 9th or 10th of September 2022, my Home Assistant logs are filling over a 24hr period with the same error message, showing it cannot connect on port 502 to the FoxESS inverter. All routers have been rebooted and cables reseated. This continual log filling causes the device to hang and crash, requiring a power cycle.

Is anyone else having a similar issue?

Error message as below:

Logger: pymodbus.client.sync
Source: components/modbus/modbus.py:380 
First occurred: 10:03:18 (467 occurrences) 
Last logged: 10:26:52

Connection to (192.168.xx.xx, 502) failed: timed out

**Comment by macxq** [comment]
this integration is not communicating over the modbus ...
