### ISSUE TITLE
Data from FoxESS - Energy Generated differ quote a lot from the FoxESS app

### ISSUE THREAD

**Issue by spitfire** [macxq/foxess-ha#90]
Data your plugin shows for total power generation differ quite a lot from what I see in the FoxESS app.
For example today's **FoxESS - Energy Generated** was 11,1 kWh, while FoxESS app claims the same inverter generated 15,2 kWh - why is there such a big difference?
I don't have a battery system, just a T8-G3 inverter

**Comment by amamoh** [comment]
Same here T4-G3

**Comment by Bartolini177** [comment]
In my issue, I described why they are given. I'm waiting for someone to say something about it.

https://github.com/macxq/foxess-ha/issues/92

**Comment by prezes210** [comment]
Same here `Fox T6`

**Comment by macxq** [comment]
Duplicate https://github.com/macxq/foxess-ha/issues/92
