### ISSUE TITLE
I’m unable to get the sensor data

### ISSUE THREAD

**Issue by up661114** [macxq/foxess-ha#91]
Hi, 

I’m not sure what I am doing wrong, I’ve followed the steps in the guide as best I can but I don’t seem to get any sensor data but also no errors to help me find out what’s gone wrong. Can someone help? 
![98F6103C-C900-4F2C-9DB2-4B52055A9F2A](https://user-images.githubusercontent.com/15279708/200761888-bcc08274-b67f-4da3-8cbe-7e1778a8ab57.png)
![26676E34-895D-49C7-A71D-5ED3A670D685](https://user-images.githubusercontent.com/15279708/200761898-961e3cf3-ce26-4f7d-bce1-ed93bd4bb23f.png)
![A5AEF33C-56AF-4AD3-A22C-17159C24041D](https://user-images.githubusercontent.com/15279708/200761901-d10dd4f8-855f-4694-aca1-4580cdebf52b.jpeg)

**Comment by alexmercerscott** [comment]
There is an ongoing issue for Home Assistant users who upgraded to 2022.11.x recently. This HACS integration seems to have stopped, and so far we haven't heard of any fixes.

The original issue is here #83

**Comment by up661114** [comment]
> There is an ongoing issue for Home Assistant users who upgraded to 2022.11.x recently. This HACS integration seems to have stopped, and so far we haven't heard of any fixes.
> 
> The original issue is here #83

Hi thanks for your update. Can I ask what the last stable version it worked on so I can downgrade and use this integration?

**Comment by alexmercerscott** [comment]
> > There is an ongoing issue for Home Assistant users who upgraded to 2022.11.x recently. This HACS integration seems to have stopped, and so far we haven't heard of any fixes.
> > The original issue is here #83
> 
> Hi thanks for your update. Can I ask what the last stable version it worked on so I can downgrade and use this integration?

For me, it was 2022.10.5. If I roll back to that back-up, it works fine.

**Comment by up661114** [comment]
> > > There is an ongoing issue for Home Assistant users who upgraded to 2022.11.x recently. This HACS integration seems to have stopped, and so far we haven't heard of any fixes.
> > > The original issue is here #83
> > 
> > 
> > Hi thanks for your update. Can I ask what the last stable version it worked on so I can downgrade and use this integration?
> 
> For me, it was 2022.10.5. If I roll back to that back-up, it works fine.

Great thanks for info I shall try to downgrade and set it up 😄

**Comment by up661114** [comment]
> > > There is an ongoing issue for Home Assistant users who upgraded to 2022.11.x recently. This HACS integration seems to have stopped, and so far we haven't heard of any fixes.
> > > The original issue is here #83
> > 
> > 
> > Hi thanks for your update. Can I ask what the last stable version it worked on so I can downgrade and use this integration?
> 
> For me, it was 2022.10.5. If I roll back to that back-up, it works fine.

I tried but it still does not work, does it matter what version of FOXESS integration I download? I just can't seem to find any way to make it work.

**Comment by alexmercerscott** [comment]
The only version I've tried is the current HACS 0.15 version. Sorry I cannot be of further help. Keep an eye on the other reports though. Perhaps the ongoing current issue is also your issue. #83

**Comment by macxq** [comment]
fixed in v0.16 thanks to @guba91
