### ISSUE TITLE
1 Hybrid Inverter & 1 non-hybrid inverter which is connected to the Hybrid Data to Foxess Cloud only from Hybrid

### ISSUE THREAD

**Issue by rjhazeld** [macxq/foxess-ha#94]
I am new to HA but have set HA up with this integration but only get data from one string of panels (PV1) which are connected to the Hybrid Inverter. The second string, connected to the non-hybrid inverter, appears in the real time data panels of the Foxess app and webpage as PVPower. On the system diagram it appears lower right as 'inverter'. (See the images attached).

As far as I can tell the PVPower reading is not collected or not extracted from the data collected. Have I missed something or is there a workaround? Looking at the code it would _seem_ that copying the PV1Power pieces and renaming PV1Power, PVPower. would work but cause problems with updates to the base code in the future.

![Foxess webdiagram](https://user-images.githubusercontent.com/10947568/203297488-60a1adcb-61f4-452c-9581-9bf9edcecd18.jpg)
![Foxess realData ](https://user-images.githubusercontent.com/10947568/203297496-de83b253-f88c-41cb-89dc-15fe1d19a9f6.jpg)

**Comment by Daibutt** [comment]
I'm not sure where your non hybrid inverter input would appear in the Fox data, but I was under the impression PVPower was the sum of strings 1-4 on the hybrid.
![image](https://user-images.githubusercontent.com/69276073/203315302-dd8e82b6-aa0c-49a4-b625-8aad96a3d063.png)
Have you tried asking at https://www.facebook.com/groups/foxessownersgroup ?
There are a few people on there with multi inverters using HA.

**Comment by rjhazeld** [comment]
Thanks for your quick reply. You are quite right by some fluke both strings were producing the same amount when I was looking at it. Back to the drawing board as I can't see where they are drawing the information from to populate the second inverter other than it originates from a ct clamp on the non-hybrid to CT2 on the hybrid.

**Comment by Daibutt** [comment]
Is there anything under the dropdown on the stats graph? There are a load of parameters there. On mine I couldn't see anything that looked like "CT2" or "2nd inverter" but then I only one inverter.
![image](https://user-images.githubusercontent.com/69276073/203350994-9c186bac-babe-4521-8f8c-47cf5e39c36f.png)

**Comment by rjhazeld** [comment]
Thanks for the follow up I examined the drop box as suggested but found nothing on the face of it that applied. However, I had previously found a Foxess cloud API document in which there is mention of an error code id 15 which refers to Meter/CT lost - Meter Communication fault. Looking at the drop down list on the web page again I see that there is meterPower and meterPower2. Searching them both produces graphs lines, meterPower looks to be identical to grid consumption - from CT1 clamp on the meter positive cable between the meter and consumer unit. and I think meterPower2 is the one I am looking for CT2 clamp which is on the A/C out positive cable of the non-hybrid inverter. There are corresponding meterStatus items as well but I don't know whether they are useful or not.

Looking at the HA code I can't see these fields being pulled in under those names. So the question is if those names exist in the data how can it be pulled in and attached to a sensor?

**Comment by Daibutt** [comment]
That maybe something @macxq can help with with the meterPower2 data point?

**Comment by rjhazeld** [comment]
Sorry it should be meter2power.
