### ISSUE TITLE
stopped working an all 2022_11 Releases

### ISSUE THREAD

**Issue by volker67** [macxq/foxess-ha#98]
### Discussed in https://github.com/macxq/foxess-ha/discussions/97

<div type='discussions-op-text'>

<sup>Originally posted by **volker67** November 30, 2022</sup>
I used to update my hassio installation. But cannot update to 2022.11.1 - 5
FoxEss Integration stopped working.
All entities are in "Restored" State.

when i rollback with  ha core update --version=2022.10.5
everything is ok.

that is the part in my sensor.yaml

  - platform: foxess
    name: Dach-5KW
    username: xxx
    password: xxx
    deviceID: <my-device-id>
    
  - platform: foxess
    name: Dach-10KW
    username: xxx
    password: xxx
    deviceID: <my-device-id>

</div>

**Comment by volker67** [comment]
ok - solved it - thanks to [cosmico89](https://github.com/cosmico89)
https://github.com/macxq/foxess-ha/issues/93#issuecomment-1319326849

**Comment by macxq** [comment]
fixed in v0.16 thanks to @guba91
