### ISSUE TITLE
daily_pv1_sum not working

### ISSUE THREAD

**Issue by up661114** [macxq/foxess-ha#99]
I have some of this working but I get negative solar readings, the thing I thought would solve this was daily_pv1_sum but this never seems to work, is there a thing I need to do to get this to work?

**Comment by up661114** [comment]
# Setup Better Solar Tracking Sensors that resolve negative solar tracking  

  - platform: integration
    source: sensor.foxess_pv1_power
    name: pv1_sum
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.foxess_pv2_power
    name: pv2_sum
    unit_time: h
    round: 2
    
# Setup Daily and real-time solar trackers that resolve the negative solar tracking    

utility_meter:
    daily_pv1_sum:
        source: sensor.pv1_sum
        cycle: daily
 
    daily_pv2_sum:
        source: sensor.pv2_sum
        cycle: daily
        
# Setup Daily and real-time solar trackers that resolve the negative solar tracking   
       
template:
  - sensor:
      - name: "Solar Power Daily"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.daily_pv1_sum') | float + states('sensor.daily_pv2_sum') | float }}"
 
      - name: "Solar Power Now"
        unit_of_measurement: "kW"
        state: "{{ states('sensor.foxess_pv1_power') | float + states('sensor.foxess_pv2_power') | float }}"

**Comment by up661114** [comment]
This is what I have put inside my yaml

**Comment by Daibutt** [comment]
Which part is not working? daily_pv1_sum?
Working backwards through the logic...
Does your pv1_sum sensor show a value?
If not is your sensor.foxess_pv1_power showing values?
Are they all named correctly (underscore vs dash)? I have seen a couple with pv1-power rather than pv1_power

I'm not sure the bottom code for the totals will stop negative values, but as an aside, a while back the format changed and it might be worth replacing "float" with "float(default=0)"

**Comment by up661114** [comment]
![image](https://user-images.githubusercontent.com/15279708/205663385-f227ebf6-7d0f-4ab7-830d-327b8b4d6c5d.png)

**Comment by Daibutt** [comment]
OK. What is the last graph - is that daily_pv_sum or Foxess_solar ?

**Comment by up661114** [comment]
![image](https://user-images.githubusercontent.com/15279708/205873728-490a6551-5c85-46ad-a462-607bdd38237d.png)

**Comment by up661114** [comment]
I have one 4kwp array

**Comment by up661114** [comment]
My sensor for the foxes system work but these extra calculations for daily_pv_1_sum etc don't seem to do anything.   I think basically the part that I have copied to try and get rid of the negative numbers isn't working.

**Comment by up661114** [comment]
Sorry if my explanations are not great I am new to HA and FoxESS

**Comment by up661114** [comment]
This is what I copied into my config.yaml

**Comment by up661114** [comment]
Setup Better Solar Tracking Sensors that resolve negative solar tracking  

  - platform: integration
    source: sensor.foxess_pv1_power
    name: pv1_sum
    unit_time: h
    round: 2

    
# Setup Daily and real-time solar trackers that resolve the negative solar tracking    

utility_meter:
    daily_pv1_sum:
        source: sensor.pv1_sum
        cycle: daily
 

        
# Setup Daily and real-time solar trackers that resolve the negative solar tracking   
       
template:
  - sensor:
      - name: "Solar Power Daily"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.daily_pv1_sum') | float + states('sensor.daily_pv2_sum') | float }}"
 
      - name: "Solar Power Now"
        unit_of_measurement: "kW"
        state: "{{ states('sensor.foxess_pv1_power') | float + states('sensor.foxess_pv2_power') | float }}"

**Comment by Daibutt** [comment]
OK let's go through this in stages.
Your PV1 sensor has a name that is sensor.xxxxxxxx, without knowing that you can't set up the rest of it correctly.
On a HA screen, hit the search icon and search for Fox. Scroll until you find the FoxESS PV1 Power entity and copy exactly the sensor name in grey.

I don't have the Foxcloud integration so don't have sensors with "Fox" in the name so the picture attached is me searching for "pv1", you need to use "Fox".
![image](https://user-images.githubusercontent.com/69276073/205879004-b29a71c9-6eaf-4997-b6bb-783918823954.png)

Once you have the name, post it here and we'll look at PV1_sum.

**Comment by up661114** [comment]
![image](https://user-images.githubusercontent.com/15279708/205881246-faf1b952-d165-4bf9-a25d-deb3404e1e65.png)

**Comment by up661114** [comment]
I found it as sensor.foxess1_pv1_power

**Comment by Daibutt** [comment]
OK that would explain at least part of the problem...... foxess1 not foxess

You need to change the code for the pv1_sum sensor to use that name not sensor.foxess_pv1_power

platform: integration
source: sensor.foxess1_pv1_power
name: pv1_sum
unit_time: h
round: 2

Try that, you may need to reboot HA after for the code change to update, then give it a bit of time for pv1_sum to start registering (depending how much sun you have)

**Comment by up661114** [comment]
Great! Thanks so much for helping me work this out! 😄

**Comment by Daibutt** [comment]
No worries, glad it seems to be working. 
Your dashboard will look a bit odd for today as you only have half a day of pv1_sum readings, but from tomorrow hopefully it will look a lot better.

**Comment by Daibutt** [comment]
@up661114 How is your energy dashboard looking today? Can we close this issue out?
